from stage6_ingestion.canonical import canonical_hash,without
SCHEMA_VERSION="STAGE6_EVENT_EXPOSURE_DIMENSION_MATCH_V1"
def event_qualifier_id(event,item,policy_hash,processor):return "S6EVENTDIM_"+canonical_hash({"event_id":event["event_id"],"event_version":event["event_version"],"event_hash":event["record_hash"],"event_field":item["event_field"],"event_dimension_value":item["event_dimension_value"],"dimension_type":item["dimension_type"],"dimension_entity_id":item["dimension_entity_id"],"evidence_refs":item["evidence_refs"],"policy_hash":policy_hash,"processor_version":processor})[:24]
def deterministic_match_id(qualification,event,items,policy_hash,processor):return "S6DIMMATCH_"+canonical_hash({"schema_version":SCHEMA_VERSION,"qualification_id":qualification["qualification_id"],"qualification_hash":qualification["record_hash"],"event_id":event["event_id"],"event_version":event["event_version"],"event_hash":event["record_hash"],"event_qualifiers":items,"policy_id":"S6DIMMATCHPOL_STAGE6_3E_V1","policy_hash":policy_hash,"processor_version":processor})[:24]
def build_dimension_match(*,qualification,transmission,binding,event,event_registry,event_qualifiers,policy,policy_hash):
 rules={r["source_rule_id"]:r for r in policy["rules"]};paths=transmission["transmission_paths"];rule=rules.get(transmission.get("rule_id"));items=sorted(event_qualifiers,key=lambda x:(x["event_field"],x["event_dimension_value"],x["dimension_type"],x["dimension_entity_id"]));items=[{"event_qualifier_id":event_qualifier_id(event,x,policy_hash,policy["processor_version"]),**x} for x in items]
 if not paths:qualification_status="NOT_REQUIRED";qualified=[];unqualified=[]
 elif rule["dimension_mode"]=="NOT_REQUIRED":qualification_status="NOT_REQUIRED";qualified=[];unqualified=[]
 else:
  values=sorted(event[rule["event_field"]]);qualified=sorted({x["event_dimension_value"] for x in items});unqualified=sorted(set(values)-set(qualified));qualification_status="ALL_QUALIFIED" if values and not unqualified else "PARTIALLY_QUALIFIED" if qualified and unqualified else "UNQUALIFIED"
 exposure_by_path={}
 for q in qualification["qualifiers"]:exposure_by_path.setdefault(q["source_path_id"],set()).add(q["dimension_entity_id"])
 event_ids=sorted({x["dimension_entity_id"] for x in items});matches=[]
 for path in paths:
  path_rule=rules[path["rule_id"]]
  if path_rule["dimension_mode"]=="NOT_REQUIRED":eids=[];xids=[];matched=[];status="NOT_REQUIRED";dtype=None
  else:
   dtype=path_rule["dimension_type"];eids=sorted(x["dimension_entity_id"] for x in items if x["dimension_type"]==dtype);xids=sorted(exposure_by_path.get(path["path_id"],set()));matched=sorted(set(eids)&set(xids))
   status="EXACT_ENTITY_MATCH" if matched else "NO_ENTITY_MATCH" if qualification_status=="ALL_QUALIFIED" and xids else "INDETERMINATE"
  matches.append({"source_path_id":path["path_id"],"source_rule_id":path["rule_id"],"source_rule_hash":path["rule_hash"],"assertion_hash":path["assertion_hash"],"exposure_type":path["exposure_type"],"dimension_type":dtype,"event_dimension_entity_ids":eids,"exposure_dimension_entity_ids":xids,"matched_dimension_entity_ids":matched,"dimension_match_status":status})
 matches.sort(key=lambda x:x["source_path_id"]);required=[x for x in matches if x["dimension_match_status"]!="NOT_REQUIRED"]
 if not paths:overall="NO_COMPATIBLE_PATHS"
 elif not required:overall="DIMENSION_NOT_REQUIRED_ONLY"
 elif any(x["dimension_match_status"]=="INDETERMINATE" for x in required):overall="INDETERMINATE_DIMENSION_MATCH"
 elif all(x["dimension_match_status"]=="EXACT_ENTITY_MATCH" for x in required):overall="ALL_REQUIRED_DIMENSIONS_MATCH"
 elif all(x["dimension_match_status"]=="NO_ENTITY_MATCH" for x in required):overall="NO_REQUIRED_DIMENSIONS_MATCH"
 else:overall="PARTIAL_REQUIRED_DIMENSIONS_MATCH"
 out={"schema_version":SCHEMA_VERSION,"match_id":"","record_hash":"0"*64,"qualification_id":qualification["qualification_id"],"qualification_hash":qualification["record_hash"],"transmission_id":qualification["transmission_id"],"transmission_hash":qualification["transmission_hash"],"binding_id":qualification["binding_id"],"binding_hash":qualification["binding_hash"],"event_id":event["event_id"],"event_version":event["event_version"],"event_hash":event["record_hash"],"exposure_id":qualification["exposure_id"],"exposure_version":qualification["exposure_version"],"exposure_hash":qualification["exposure_hash"],"company_entity_id":qualification["company_entity_id"],"sector_entity_id":qualification["sector_entity_id"],"subsector_entity_id":qualification["subsector_entity_id"],"event_entity_registry_snapshot_id":event_registry["registry_snapshot_id"],"event_entity_registry_version":event_registry["registry_version"],"event_entity_registry_hash":event_registry["registry_hash"],"exposure_entity_registry_snapshot_id":qualification["entity_registry_snapshot_id"],"exposure_entity_registry_version":qualification["entity_registry_version"],"exposure_entity_registry_hash":qualification["entity_registry_hash"],"match_cutoff_timestamp":qualification["qualification_cutoff_timestamp"],"event_dimension_qualification_status":qualification_status,"qualified_event_dimension_values":qualified,"unqualified_event_dimension_values":unqualified,"event_qualifiers":items,"path_matches":matches,"dimension_compatibility_status":overall,"semantic_compatibility_status":"NOT_EVALUATED","trade_role_semantics_status":"NOT_EVALUATED","directional_effect_status":"NOT_EVALUATED","magnitude_status":"NOT_EVALUATED","causal_effect_status":"NOT_EVALUATED","policy_id":policy["policy_id"],"policy_hash":policy_hash,"processor_version":policy["processor_version"],"authority":policy["authority"]};out["match_id"]=deterministic_match_id(qualification,event,items,policy_hash,policy["processor_version"]);out["record_hash"]=canonical_hash(without(out,"record_hash"));return out
