from datetime import datetime,timezone
from copy import deepcopy
from stage6_ingestion.canonical import canonical_hash,without
from .policy import *

SAFETY={"outcome_status":"NOT_ATTACHED","execution_status":"NOT_AUTHORIZED","order_creation_status":"NOT_AUTHORIZED","order_cancellation_status":"NOT_AUTHORIZED","stage5d_mutation_status":"PROHIBITED","network_calls":0,"external_api_calls":0,"broker_calls":0,"market_downloads":0,"news_downloads":0,"llm":False,"nlp":False,"ml":False,"ocr":False,"embeddings":False,"semantic_similarity":False,"trading_authority":False}
def now_utc():return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00","Z")
def binding(t,i,h):return {"record_type":t,"record_id":i,"record_hash":h}
def finish(prefix,record,id_field):
 record[id_field]=prefix+canonical_hash(without(record,id_field,"record_hash"))[:24];record["record_hash"]=canonical_hash(without(record,"record_hash"));return record
def build_session(activation,protocol_hash,control_database_id,run,ordinal):
 ab=binding(ACTIVATION_SCHEMA,activation["activation_id"],activation["record_hash"]);pb=binding(PROTOCOL_ID,PROTOCOL_ID,protocol_hash);rb=binding(CONTROL_SCHEMA,run["run_id"],run["payload_sha256"])
 record={"schema_version":SESSION_SCHEMA,"enrollment_id":"","activation_binding":ab,"protocol_binding":pb,"control_database_id":control_database_id,"control_run_binding":rb,"stage5d5_run_id":run["run_id"],"stage5d5_run_payload_hash":run["payload_sha256"],"market_session_date":run["market_session_date"],"run_started_utc":run["run_started_utc"],"run_completed_utc":run["run_completed_utc"],"candidate_count":run["candidate_count"],"recommendation_count":run["recommendation_count"],"news_status":run["news_status"],"allocation_run_id":run["allocation_run_id"],"management_session_run_id":run["management_session_run_id"],"stage4a3_snapshot_id":run["stage4a3_snapshot_id"],"market_data_hash":run["market_data_hash"],"candidate_input_hash":run["candidate_input_hash"],"prospective_eligibility":"PASS","session_ordinal_since_activation":ordinal,"zero_candidate_flag":run["candidate_count"]==0,"zero_recommendation_flag":run["recommendation_count"]==0,"direct_dependencies":[ab,pb,rb],"authority":AUTHORITY,"trading_authority":False,"record_hash":""};return finish("S6PROSSESS_",record,"enrollment_id")
def build_submission(activation,proposal,submitted_at):
 pb=binding(SHADOW_SCHEMA,proposal["proposal_id"],proposal["record_hash"]);ab=binding(ACTIVATION_SCHEMA,activation["activation_id"],activation["record_hash"])
 record={"schema_version":"STAGE6_PROSPECTIVE_SHADOW_SUBMISSION_V1","submission_id":"","proposal_binding":pb,"activation_binding":ab,"submitted_at_utc":submitted_at,"target_session_date":proposal["target_session_date"],"recommendation_id":proposal["recommendation_id"],"ticker":proposal["ticker"],"proposal_decision":proposal["proposal_decision"],"proposal_reason_code":proposal["proposal_reason_code"],"proposal_cutoff":proposal["proposal_cutoff"],"session_timing_status":proposal.get("session_timing_status","BOUND_STAGE6_7A_SNAPSHOT_REQUIRED"),"authority":AUTHORITY,"record_hash":""};return finish("S6PROSSUB_",record,"submission_id")
def build_case(activation,protocol_hash,origin_session,target_session,recommendation,pending,calendar_proof,submission=None,enrolled_at=None):
 enrolled_at=enrolled_at or now_utc();ab=binding(ACTIVATION_SCHEMA,activation["activation_id"],activation["record_hash"]);pb=binding(PROTOCOL_ID,PROTOCOL_ID,protocol_hash);origin=binding(SESSION_SCHEMA,origin_session["enrollment_id"],origin_session["record_hash"]);target=binding(SESSION_SCHEMA,target_session["enrollment_id"],target_session["record_hash"]);rb=binding("STAGE5D_RECOMMENDATION",recommendation["recommendation_id"],recommendation["payload_sha256"]);eb=binding("STAGE5D_PENDING_ENTRY_EVENT",pending["event_id"],pending["payload_sha256"]);shadow=None if submission is None else binding(submission["schema_version"],submission["submission_id"],submission["record_hash"]);deps=[ab,pb,origin,target,rb,eb,*([shadow] if shadow else [])]
 record={"schema_version":CASE_SCHEMA,"case_id":"","activation_binding":ab,"protocol_binding":pb,"control_origin_session_binding":origin,"control_session_binding":target,"target_session_calendar_proof":deepcopy(calendar_proof),"control_recommendation_binding":rb,"pending_entry_event_binding":eb,"shadow_submission_binding":shadow,"recommendation_id":recommendation["recommendation_id"],"ticker":recommendation["ticker"],"target_session_date":target_session["market_session_date"],"control_recommendation_date":recommendation["decision_date"],"selected_horizon":recommendation["selected_horizon"],"stage6_proposal_decision":None if submission is None else submission["proposal_decision"],"stage6_proposal_reason_code":None if submission is None else submission["proposal_reason_code"],"shadow_availability":"NOT_SUBMITTED" if submission is None else "AVAILABLE","case_state":"CONTROL_ONLY_PENDING_SHADOW" if submission is None else "PAIRED_SHADOW_AVAILABLE","enrolled_at_utc":enrolled_at,"direct_dependencies":deps,"authority":AUTHORITY,**SAFETY,"record_hash":""};return finish("S6PROSCASE_",record,"case_id")
