from stage6_ingestion.canonical import canonical_hash,without
SCHEMA_VERSION="STAGE6_MOVEMENT_AWARE_PATH_EFFECT_V1"
def pair_id(path_id,movement_item_id):return "S6PATHEFFPAIR_"+canonical_hash({"source_path_id":path_id,"movement_item_id":movement_item_id})[:24]
def eligible_pairs(match,movement,policy):
 rule={x["event_type"]:x for x in policy["rules"]}.get(movement["event_type"]);out=[]
 if rule is None:return out
 for path in match["path_matches"]:
  if path["source_rule_id"]!=rule["source_rule_id"] or path["dimension_match_status"]!="EXACT_ENTITY_MATCH":continue
  for item in movement["movement_items"]:
   if item["movement_kind"]==rule["movement_kind"] and item["movement_metric"]==rule["movement_metric"] and item["source_dimension_entity_id"] in path["matched_dimension_entity_ids"]:out.append({"path_effect_pair_id":pair_id(path["source_path_id"],item["movement_item_id"]),"source_path_id":path["source_path_id"],"movement_item_id":item["movement_item_id"],"movement_subject_entity_id":item["source_dimension_entity_id"],"movement_reference_entity_id":item["reference_dimension_entity_id"],"movement_metric":item["movement_metric"],"movement_direction":item["movement_direction"],"effect_rule_id":rule["rule_id"],"effect_rule_hash":canonical_hash(rule)})
 return sorted(out,key=lambda x:(x["source_path_id"],x["movement_item_id"]))
def effect_item_id(movement,item,policy_hash,processor):return "S6PATHEFFITEM_"+canonical_hash({"movement_record_id":movement["movement_record_id"],"movement_record_hash":movement["record_hash"],**item,"policy_hash":policy_hash,"processor_version":processor})[:24]
def record_id(movement,items,policy_hash,processor):return "S6PATHEFF_"+canonical_hash({"schema_version":SCHEMA_VERSION,"movement_record_id":movement["movement_record_id"],"movement_record_hash":movement["record_hash"],"effect_items":items,"policy_id":"S6PATHEFFPOL_STAGE6_3H_V1","policy_hash":policy_hash,"processor_version":processor})[:24]
def build_path_effect(*,movement,match,exposure,effect_items,policy,policy_hash):
 pairs=eligible_pairs(match,movement,policy);items=sorted(effect_items,key=lambda x:(x["source_path_id"],x["movement_item_id"]));items=[{"path_effect_item_id":effect_item_id(movement,x,policy_hash,policy["processor_version"]),**x} for x in items];by_pair={x["path_effect_pair_id"]:x for x in items};eligible=[x["path_effect_pair_id"] for x in pairs];qualified=sorted(by_pair);unqualified=sorted(set(eligible)-set(qualified));status="NO_ELIGIBLE_PATH_EFFECTS" if not eligible else "UNQUALIFIED" if not qualified else "PARTIALLY_QUALIFIED" if unqualified else "ALL_ELIGIBLE_PATH_EFFECTS_QUALIFIED";results=[]
 for pair in pairs:
  item=by_pair.get(pair["path_effect_pair_id"]);results.append({**pair,"eligibility_status":"ELIGIBLE","effect_direction":item["effect_direction"] if item else None})
 if status=="NO_ELIGIBLE_PATH_EFFECTS":summary="NOT_EVALUATED"
 elif status!="ALL_ELIGIBLE_PATH_EFFECTS_QUALIFIED":summary="INDETERMINATE"
 else:
  effects={x["effect_direction"] for x in items};summary="INDETERMINATE" if "UNKNOWN" in effects else "FAVORABLE_ONLY" if effects=={"FAVORABLE"} else "ADVERSE_ONLY" if effects=={"ADVERSE"} else "MIXED_PATH_DIRECTIONS"
 out={"schema_version":SCHEMA_VERSION,"path_effect_record_id":"","record_hash":"0"*64,"movement_record_id":movement["movement_record_id"],"movement_record_hash":movement["record_hash"],"match_id":match["match_id"],"match_hash":match["record_hash"],"event_id":match["event_id"],"event_version":match["event_version"],"event_hash":match["event_hash"],"event_type":movement["event_type"],"exposure_id":match["exposure_id"],"exposure_version":match["exposure_version"],"exposure_hash":match["exposure_hash"],"company_entity_id":match["company_entity_id"],"path_effect_cutoff_timestamp":movement["movement_cutoff_timestamp"],"path_effect_scope":"MATCHED_MOVEMENT_EXPOSURE_PATH_ONLY","eligible_path_effect_pair_ids":eligible,"qualified_path_effect_pair_ids":qualified,"unqualified_path_effect_pair_ids":unqualified,"path_effect_qualification_status":status,"effect_items":items,"path_effect_results":results,"matched_movement_path_effect_summary":summary,"overall_company_effect_status":"NOT_EVALUATED","stock_direction_status":"NOT_EVALUATED","market_reaction_status":"NOT_EVALUATED","magnitude_status":"NOT_EVALUATED","expected_return_status":"NOT_EVALUATED","causal_effect_status":"NOT_EVALUATED","portfolio_influence_status":"NOT_EVALUATED","trading_authority":False,"policy_id":policy["policy_id"],"policy_hash":policy_hash,"processor_version":policy["processor_version"],"authority":policy["authority"]};out["path_effect_record_id"]=record_id(movement,items,policy_hash,policy["processor_version"]);out["record_hash"]=canonical_hash(without(out,"record_hash"));return out
