from copy import deepcopy
from stage6_ingestion.canonical import canonical_hash,without,parse_utc
from .policy import *

SAFETY={"pending_entry_status":"FROZEN","current_thesis_status":"FROZEN","review_inputs_status":"FROZEN","pit_validation_status":"PASS","session_timing_status":"CALLER_DECLARED_PRE_SESSION","entry_revalidation_status":"NOT_EVALUATED","entry_proposal_status":"NOT_MATERIALIZED","stage5d_mutation_status":"PROHIBITED","portfolio_mutation_status":"PROHIBITED","thesis_mutation_status":"PROHIBITED","buy_sell_hold_status":"NOT_EVALUATED","network_calls":0,"external_api_calls":0,"market_data_downloads":0,"stage5d_live_database_calls":0,"broker_calls":0,"llm":False,"nlp":False,"ml":False,"ocr":False,"embeddings":False,"semantic_similarity":False,"trading_authority":False}
def binding(t,i,h):return {"record_type":t,"record_id":i,"record_hash":h}
def build_snapshot(*,portfolio,pending,source,source_record_id,thesis,target_session_date,revalidation_cutoff,evidence,effects,market,analogue,policy_hash,contract_hash):
 pb=binding(PORTFOLIO_SCHEMA,portfolio["portfolio_context_id"],portfolio["record_hash"]);tb=binding(THESIS_SCHEMA,thesis["thesis_id"],thesis["record_hash"])
 eb=sorted([binding("STAGE6_EVIDENCE_V2",x["evidence_id"],x["record_hash"]) for x in evidence],key=lambda x:x["record_id"]);cb=sorted([binding("STAGE6_EVENT_COMPANY_EFFECT_V1",x["company_effect_record_id"],x["record_hash"]) for x in effects],key=lambda x:x["record_id"])
 mb=None if market is None else binding("STAGE6_MARKET_CONTEXT_V2",market["contract_payload"]["market_context_id"],market["record_hash"]);ab=None if analogue is None else binding("STAGE6_HISTORICAL_ANALOGUE_V2",analogue["historical_analogue_payload"]["historical_analogue_id"],analogue["record_hash"])
 availability={"evidence":"AVAILABLE" if eb else "NOT_PROVIDED","company_effects":"AVAILABLE" if cb else "NOT_PROVIDED","market_context":"AVAILABLE" if mb else "NOT_PROVIDED","historical_analogue":"AVAILABLE" if ab else "NOT_PROVIDED"}
 direct=[pb,tb,*eb,*cb,*([mb] if mb else []),*([ab] if ab else [])]
 elapsed=int((parse_utc(revalidation_cutoff,"revalidation")-parse_utc(thesis["decision_cutoff"],"thesis")).total_seconds())
 record={"schema_version":SNAPSHOT_SCHEMA,"morning_snapshot_id":"","target_session_date":target_session_date,"revalidation_cutoff":revalidation_cutoff,"portfolio_context_binding":pb,"pending_entry":deepcopy(pending),"recommendation_id":pending["recommendation_id"],"ticker":pending["ticker"],"thesis_id":pending["thesis_id"],"current_thesis_source":source,"current_version_record_id":source_record_id,"current_thesis_binding":tb,"thesis_version":thesis["version"],"thesis_status":thesis["thesis_status"],"thesis_decision_cutoff":thesis["decision_cutoff"],"committed_capital":deepcopy(pending["committed_capital"]),"availability":availability,"evidence_bindings":eb,"company_effect_bindings":cb,"company_effect_summaries":[{"company_effect_record_id":x["company_effect_record_id"],"company_entity_id":x.get("company_entity_id"),"event_identity":x.get("event_id"),"exposure_identity":x.get("exposure_record_id"),"company_event_effect":x["company_event_effect"]} for x in sorted(effects,key=lambda x:x["company_effect_record_id"])],"market_context_binding":mb,"historical_analogue_binding":ab,"direct_input_bindings":direct,"factual_metadata":{"evidence_count":len(eb),"company_effect_count":len(cb),"market_context_supplied":mb is not None,"historical_analogue_supplied":ab is not None,"seconds_since_thesis_cutoff":elapsed,"committed_capital":deepcopy(pending["committed_capital"]),"thesis_version":thesis["version"],"thesis_status":thesis["thesis_status"]},"processor_version":PROCESSOR,"policy_id":POLICY_ID,"policy_hash":policy_hash,"contract_version":CONTRACT_VERSION,"contract_hash":contract_hash,"authority":AUTHORITY,**SAFETY,"record_hash":""}
 record["morning_snapshot_id"]="S6MORNIN_"+canonical_hash(without(record,"morning_snapshot_id","record_hash"))[:24];record["record_hash"]=canonical_hash(without(record,"record_hash"));return record
