from copy import deepcopy
from stage6_ingestion.canonical import canonical_hash,parse_utc,utc_timestamp,without
from .policy import *

SAFETY={"previous_thesis_status":"FROZEN","review_inputs_status":"FROZEN","pit_validation_status":"PASS","material_change_status":"NOT_EVALUATED","thesis_status_evaluation":"NOT_EVALUATED","next_thesis_version_status":"NOT_MATERIALIZED","stop_change_status":"NOT_EVALUATED","target_change_status":"NOT_EVALUATED","portfolio_constraint_status":"NOT_EVALUATED","replacement_status":"NOT_EVALUATED","buy_sell_hold_status":"NOT_EVALUATED","trading_authority":False,"network_calls":0,"external_api_calls":0,"market_data_downloads":0,"broker_calls":0,"llm":False,"nlp":False,"ml":False,"ocr":False,"embeddings":False,"semantic_similarity":False}
def binding(kind,identity,digest):return {"record_type":kind,"record_id":identity,"record_hash":digest}
def availability(values):return "AVAILABLE" if values else "NOT_PROVIDED"
def portfolio_presence(payload,ticker):
 opened=any(x["ticker"]==ticker for x in payload["open_positions"]);pending=any(x["ticker"]==ticker for x in payload["pending_entries"])
 return "OPEN_AND_PENDING" if opened and pending else "OPEN_POSITION" if opened else "PENDING_ENTRY" if pending else "NOT_PRESENT"
def build_review_snapshot(*,thesis,review_cutoff,evidence,company_effects,market_context,historical_analogue,portfolio_context,policy_hash,contract_hash):
 cutoff=utc_timestamp(review_cutoff,"review_cutoff");previous=binding(TRADE_THESIS_SCHEMA,thesis["thesis_id"],thesis["record_hash"])
 ev=[binding(EVIDENCE_SCHEMA,x["evidence_id"],x["record_hash"]) for x in sorted(evidence,key=lambda x:x["evidence_id"])]
 effects=sorted(company_effects,key=lambda x:(x["event_id"],x["event_version"],x["company_effect_record_id"]));cb=[binding(COMPANY_EFFECT_SCHEMA,x["company_effect_record_id"],x["record_hash"]) for x in effects]
 summaries=[{k:deepcopy(x[k]) for k in ("company_effect_record_id","event_id","event_version","event_hash","exposure_id","exposure_version","exposure_hash","company_entity_id","company_event_effect")}|{"review_relevance":"CALLER_SELECTED_UNINTERPRETED"} for x in effects]
 mp=market_context["contract_payload"] if market_context else None;ap=historical_analogue["historical_analogue_payload"] if historical_analogue else None;pp=portfolio_context["portfolio_context"] if portfolio_context else None
 mb=binding(MARKET_SCHEMA,mp["market_context_id"],mp["record_hash"]) if mp else None;ab=binding(ANALOGUE_SCHEMA,ap["historical_analogue_id"],ap["record_hash"]) if ap else None;pb=binding(PORTFOLIO_SCHEMA,pp["portfolio_context_id"],pp["record_hash"]) if pp else None
 direct=sorted([previous,*ev,*cb,*([mb] if mb else []),*([ab] if ab else []),*([pb] if pb else [])],key=lambda x:(x["record_type"],x["record_id"]))
 seconds=(parse_utc(cutoff,"review")-parse_utc(thesis["decision_cutoff"],"prior")).total_seconds()
 record={"schema_version":SCHEMA_VERSION,"review_snapshot_id":"","previous_thesis_binding":previous,"thesis_id":thesis["thesis_id"],"thesis_version":thesis["version"],"recommendation_id":thesis["recommendation_id"],"ticker":thesis["ticker"],"prior_decision_cutoff":thesis["decision_cutoff"],"review_cutoff":cutoff,"new_evidence_status":availability(ev),"new_evidence_bindings":ev,"company_effect_status":availability(cb),"company_effect_bindings":cb,"company_effect_summaries":summaries,"market_context_status":"AVAILABLE" if mb else "NOT_PROVIDED","market_context_binding":mb,"historical_analogue_status":"AVAILABLE" if ab else "NOT_PROVIDED","historical_analogue_binding":ab,"historical_analogue_relevance":"CALLER_SELECTED_UNINTERPRETED" if ab else "NOT_PROVIDED","portfolio_context_status":"AVAILABLE" if pb else "NOT_PROVIDED","portfolio_context_binding":pb,"portfolio_subject_presence":portfolio_presence(pp,thesis["ticker"]) if pp else "NOT_PROVIDED","direct_input_bindings":direct,"factual_delta_metadata":{"new_evidence_count":len(ev),"company_effect_count":len(cb),"market_context_provided":mb is not None,"historical_analogue_provided":ab is not None,"portfolio_context_provided":pb is not None,"elapsed_seconds":seconds,"elapsed_days":seconds/86400},"processor_version":PROCESSOR_VERSION,"policy_id":POLICY_ID,"policy_hash":policy_hash,"review_input_contract_version":CONTRACT_VERSION,"review_input_contract_hash":contract_hash,"authority":AUTHORITY,**SAFETY,"record_hash":""}
 record["review_snapshot_id"]="S6THREVINPUT_"+canonical_hash(without(record,"review_snapshot_id","record_hash"))[:24];record["record_hash"]=canonical_hash(without(record,"record_hash"));return record
