from copy import deepcopy
from stage6_ingestion.canonical import canonical_hash,without
from .distribution import distribution,quantile
from .errors import Stage6HistoricalAnalogueError
from .policy import AUTHORITY,OUTCOME_ATTACHMENT_COMMIT,SCHEMA_VERSION,SELECTION_ENGINE_COMMIT
HORIZONS=("D+1","D+3","D+5","D+10","D+20")
SAFETY={"selection_status":"FROZEN","outcome_attachment_status":"FROZEN","outcome_distribution_status":"EVALUATED","relative_return_status":"EVALUATED","final_historical_analogue_status":"MATERIALIZED","expected_return_status":"NOT_EVALUATED","target_price_status":"NOT_EVALUATED","security_ranking_status":"NOT_EVALUATED","portfolio_influence_status":"NOT_EVALUATED","buy_sell_hold_status":"NOT_EVALUATED","trading_authority":False}
def _agreement(selection,outcome,target):
 pairs=((outcome["selection_record_id"],selection["selection_record_id"]),(outcome["selection_record_hash"],selection["record_hash"]),(outcome["selection_spec_hash"],selection["selection_spec_hash"]),(outcome["candidate_universe_hash"],selection["candidate_universe_hash"]),(outcome["target_feature_snapshot_id"],selection["target_feature_snapshot_id"]),(outcome["target_feature_snapshot_hash"],selection["target_feature_snapshot_hash"]),(target["feature_snapshot_id"],selection["target_feature_snapshot_id"]),(target["feature_snapshot_hash"],selection["target_feature_snapshot_hash"]),(target["selection_input_hash"],selection["target_selection_input_hash"]),(canonical_hash(target["selection_input_snapshot"]),selection["target_selection_input_hash"]),(outcome["selected_analogue_count"],selection["analogue_count"]))
 if any(a!=b for a,b in pairs):raise Stage6HistoricalAnalogueError("HISTORICAL_ANALOGUE_CROSS_STAGE_MISMATCH")
 selected=selection["selected_analogues"];attachments=outcome["analogue_attachments"]
 if len(attachments)!=len(selected):raise Stage6HistoricalAnalogueError("HISTORICAL_ANALOGUE_ATTACHMENT_COVERAGE_MISMATCH")
 for rank,(left,right) in enumerate(zip(selected,attachments),1):
  if right["selection_rank"]!=rank or any(right[key]!=left[key] for key in ("analogue_id","entity_id","event_id","historical_as_of_timestamp","similarity_score","distance","input_snapshot_hash")):raise Stage6HistoricalAnalogueError("HISTORICAL_ANALOGUE_SELECTED_BINDING_MISMATCH")
def build_historical_analogue(*,selection,outcome,target,policy,policy_hash,aggregation_contract_hash):
 _agreement(selection,outcome,target);attachments=outcome["analogue_attachments"];unit=outcome["outcome_unit"]
 labels={h:distribution([a["horizons"][h]["stock_return"]["value"] for a in attachments if a["horizons"][h]["stock_return"]["status"]=="AVAILABLE"],unit) for h in HORIZONS}
 mae=distribution([a["maximum_adverse_excursion"]["value"] for a in attachments if a["maximum_adverse_excursion"]["status"]=="AVAILABLE"],unit);mfe=distribution([a["maximum_favourable_excursion"]["value"] for a in attachments if a["maximum_favourable_excursion"]["status"]=="AVAILABLE"],unit);recovery=distribution([a["recovery_time"]["value"] for a in attachments if a["recovery_time"]["status"]=="AVAILABLE"],"TRADING_SESSIONS")
 sector={};nifty={};sector_counts={};nifty_counts={}
 for h in HORIZONS:
  sv=[];nv=[]
  for a in attachments:
   stock=a["horizons"][h]["stock_return"];sec=a["horizons"][h]["sector_return"];nif=a["horizons"][h]["nifty_return"]
   if stock["status"]==sec["status"]=="AVAILABLE":sv.append(stock["value"]-sec["value"])
   if stock["status"]==nif["status"]=="AVAILABLE":nv.append(stock["value"]-nif["value"])
  sector[h]={"value":quantile(sv,.5),"unit":unit};nifty[h]={"value":quantile(nv,.5),"unit":unit};sector_counts[h]=len(sv);nifty_counts[h]=len(nv)
 payload={"schema_version":SCHEMA_VERSION,"historical_analogue_id":"","as_of_timestamp":selection["target_as_of_timestamp"],"selection_cutoff":selection["target_selection_cutoff"],"analogue_engine_version":"STAGE6_4C_ANALOGUE_SELECTOR_V1","code_commit":SELECTION_ENGINE_COMMIT,"feature_contract_version":selection["feature_contract_version"],"feature_snapshot_hash":selection["target_feature_snapshot_hash"],"similarity_metric":selection["similarity_metric"],"feature_weights":deepcopy(selection["feature_weights"]),"selection_thresholds":{"max_distance":deepcopy(selection["max_distance"])},"eligible_universe_definition":selection["candidate_universe_version"],"eligible_date_range":{"start":selection["eligible_date_range"]["start_date"],"end":selection["eligible_date_range"]["end_date"]},"exclusion_rules":deepcopy(selection["exclusion_rules"]),"selection_input_snapshot":deepcopy(target["selection_input_snapshot"]),"selection_input_hash":target["selection_input_hash"],"selected_analogues":deepcopy(selection["selected_analogues"]),"analogue_count":selection["analogue_count"],"minimum_required_analogue_count":selection["minimum_required_analogue_count"],"outcome_definition_version":outcome["outcome_definition_version"],"outcome_unit":unit,"future_outcome_labels":labels,"maximum_adverse_excursion":mae,"maximum_favourable_excursion":mfe,"recovery_time":recovery,"relative_return_vs_sector":sector,"relative_return_vs_nifty":nifty,"record_hash":"","pit_verified":True,"authority_mode":AUTHORITY}
 identity=canonical_hash(without(payload,"historical_analogue_id","record_hash"));payload["historical_analogue_id"]="S6HAN_"+identity[:24];payload["record_hash"]=canonical_hash(without(payload,"record_hash"))
 audit={"available_stock_counts":{h:labels[h]["count"] for h in HORIZONS},"sector_relative_paired_counts":sector_counts,"nifty_relative_paired_counts":nifty_counts,"mae_count":mae["count"],"mfe_count":mfe["count"],"recovery_count":recovery["count"]}
 core={"wrapper_schema_version":"STAGE6_4E_HISTORICAL_ANALOGUE_WRAPPER_V1","selection_record_id":selection["selection_record_id"],"selection_record_hash":selection["record_hash"],"selection_engine_commit":SELECTION_ENGINE_COMMIT,"outcome_attachment_set_id":outcome["attachment_set_id"],"outcome_attachment_set_hash":outcome["attachment_set_hash"],"outcome_attachment_commit":OUTCOME_ATTACHMENT_COMMIT,"target_feature_snapshot_id":target["feature_snapshot_id"],"target_feature_snapshot_hash":target["feature_snapshot_hash"],"processor_version":policy["processor_version"],"policy_id":policy["policy_id"],"policy_hash":policy_hash,"aggregation_contract_version":"STAGE6_ANALOGUE_AGGREGATION_CONTRACT_V1","aggregation_contract_hash":aggregation_contract_hash,"historical_analogue_id":payload["historical_analogue_id"],"historical_analogue_record_hash":payload["record_hash"],"historical_analogue_payload":payload,"coverage_audit":audit,"interpretation_readiness":"INSUFFICIENT_SELECTED_ANALOGUES" if selection["analogue_count"]<selection["minimum_required_analogue_count"] else "SELECTED_ANALOGUE_REQUIREMENT_SATISFIED","authority":AUTHORITY,**SAFETY}
 digest=canonical_hash(core);return {**core,"wrapper_id":"S6HANWRAP_"+digest[:24],"wrapper_hash":digest,"record_hash":canonical_hash({**core,"wrapper_id":"S6HANWRAP_"+digest[:24],"wrapper_hash":digest})}
