from stage6_ingestion.canonical import canonical_hash,without
SCHEMA_VERSION="STAGE6_TRANSMISSION_PATH_EVALUATION_V1"
def rule_hash(r):return canonical_hash(r)
def transmission_id(binding,policy_hash,processor):return "S6TRANS_"+canonical_hash({"schema_version":SCHEMA_VERSION,"binding_id":binding["binding_id"],"binding_hash":binding["record_hash"],"policy_id":"S6TRANSPOL_STAGE6_3C_V1","policy_hash":policy_hash,"processor_version":processor})[:24]
def path_id(binding,r,a,policy_hash,processor):return "S6TRANSPATH_"+canonical_hash({"binding_id":binding["binding_id"],"binding_hash":binding["record_hash"],"rule_id":r["rule_id"],"rule_hash":rule_hash(r),"assertion_hash":a["assertion_hash"],"processor_version":processor,"policy_hash":policy_hash})[:24]
def build_transmission(binding,policy,policy_hash):
 matches=[r for r in policy["rules"] if binding["event_type"] in r["event_types"] and binding["binding_channel"]==r["binding_channel"]];r=matches[0] if matches else None;ev=[];paths=[]
 for a in binding["selected_assertions"]:
  ok=r is not None and a["exposure_type"] in r["allowed_exposure_types"];ev.append({"assertion_hash":a["assertion_hash"],"exposure_type":a["exposure_type"],"type_match_status":"TYPE_COMPATIBLE" if ok else "TYPE_INCOMPATIBLE"})
  if ok:paths.append({"path_id":path_id(binding,r,a,policy_hash,policy["processor_version"]),"rule_id":r["rule_id"],"rule_hash":rule_hash(r),"event_id":binding["event_id"],"event_version":binding["event_version"],"event_hash":binding["event_hash"],"event_type":binding["event_type"],"binding_channel":binding["binding_channel"],"assertion_hash":a["assertion_hash"],"exposure_type":a["exposure_type"],"exposure_id":binding["exposure_id"],"exposure_version":binding["exposure_version"],"exposure_hash":binding["exposure_hash"],"company_entity_id":binding["company_entity_id"],"path_semantic_status":"TYPE_COMPATIBLE","dimension_match_status":r["dimension_match_mode"]})
 ev.sort(key=lambda x:x["assertion_hash"]);paths.sort(key=lambda x:x["path_id"]);matched=sorted(x["assertion_hash"] for x in ev if x["type_match_status"]=="TYPE_COMPATIBLE");unmatched=sorted(x["assertion_hash"] for x in ev if x["type_match_status"]=="TYPE_INCOMPATIBLE")
 status="UNSUPPORTED_EVENT_CHANNEL" if r is None else "FULL_TYPE_MATCH" if matched and not unmatched else "PARTIAL_TYPE_MATCH" if matched else "NO_TYPE_MATCH"
 out={"schema_version":SCHEMA_VERSION,"transmission_id":transmission_id(binding,policy_hash,policy["processor_version"]),"record_hash":"0"*64,"binding_id":binding["binding_id"],"binding_hash":binding["record_hash"],"event_id":binding["event_id"],"event_version":binding["event_version"],"event_hash":binding["event_hash"],"event_type":binding["event_type"],"exposure_id":binding["exposure_id"],"exposure_version":binding["exposure_version"],"exposure_hash":binding["exposure_hash"],"company_entity_id":binding["company_entity_id"],"sector_entity_id":binding["sector_entity_id"],"subsector_entity_id":binding["subsector_entity_id"],"binding_channel":binding["binding_channel"],"type_compatibility_status":status,"assertion_evaluations":ev,"matched_assertion_hashes":matched,"unmatched_assertion_hashes":unmatched,"transmission_paths":paths,"rule_id":r["rule_id"] if r else None,"rule_hash":rule_hash(r) if r else None,"semantic_compatibility_status":"NOT_EVALUATED","directional_effect_status":"NOT_EVALUATED","magnitude_status":"NOT_EVALUATED","causal_effect_status":"NOT_EVALUATED","evaluation_cutoff_timestamp":binding["binding_cutoff_timestamp"],"policy_id":policy["policy_id"],"policy_hash":policy_hash,"processor_version":policy["processor_version"],"authority":policy["authority"]};out["record_hash"]=canonical_hash(without(out,"record_hash"));return out
