"""Build deterministic metadata-only artifacts for the authoritative-data stage."""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from common import file_sha256, record, sha256
from authoritative_data import feature_pit_readiness, market_data_readiness, readiness_v3


def save(name: str, value: object) -> None:
    (ROOT / "results" / name).write_text(json.dumps(value, indent=2, sort_keys=True) + "\n", encoding="utf-8")


products = [
    {"product_id":"NSE_CM_EOD_HISTORICAL","provider":"National Stock Exchange of India","product_name":"EOD / Historical Data - Capital Market","dataset_purpose":"Official EOD bhavcopy, security and trade-detail history","market_scope":"NSE Capital Market","historical_coverage_advertised":"Historical; exact deliverable coverage subject to provider","granularity":"daily and trade/order detail by product","fields_advertised":["EOD bhavcopy","security details","trade details"],"delivery_format":"SFTP or online product delivery","source_classification":"OFFICIAL_SUBSCRIPTION_REQUIRED","machine_readable":True,"acquisition_mechanism":"official subscription","licence_status":"OFFICIAL_COMMERCIAL_LICENCE_REQUIRED","redistribution_status":"RESTRICTED","raw_data_commit_allowed":False,"derived_data_commit_allowed":False,"usage_scope":"LICENSE_TERMS_CONTROLLED_RESEARCH","official_reference":"https://betanseapi.nseindia.com/static/market-data/eod-historical-data-subscription","verification_date":"2026-10-04","research_profiles":["EXCHANGE_WIDE_PIT","INDEX_CONSTITUENT_PIT"],"readiness_gates":["market_data","security_reference","liquidity"],"acquisition_status":"SUBSCRIPTION_REQUIRED"},
    {"product_id":"NSE_SECURITIES_MASTER","provider":"National Stock Exchange of India","product_name":"Securities master / equity security list","dataset_purpose":"Security identity and reference fields","market_scope":"NSE Capital Market","historical_coverage_advertised":"Current report; complete dated historical series not established","granularity":"snapshot","fields_advertised":["symbol","ISIN","company","series","listing date"],"delivery_format":"CSV/report","source_classification":"OFFICIAL_PUBLIC_VERIFIED","machine_readable":True,"acquisition_mechanism":"official report download","licence_status":"PUBLIC_ACCESS_TERMS_APPLY","redistribution_status":"LICENCE_RESTRICTIONS_UNKNOWN","raw_data_commit_allowed":False,"derived_data_commit_allowed":True,"usage_scope":"RESEARCH_ONLY","official_reference":"https://www.nseindia.com/static/products-services/equity-market-data-reports-download","verification_date":"2026-10-04","research_profiles":["EXCHANGE_WIDE_PIT"],"readiness_gates":["identity","current_snapshot"],"acquisition_status":"PUBLICLY_ACQUIRED"},
    {"product_id":"NSE_PUBLIC_REPORT_ARCHIVE","provider":"National Stock Exchange of India","product_name":"All Reports / historical reports","dataset_purpose":"Public daily and historical exchange reports","market_scope":"NSE markets","historical_coverage_advertised":"Varies by report","granularity":"daily/monthly/report","fields_advertised":["bhavcopy","price-volume","reference reports"],"delivery_format":"CSV/ZIP/PDF","source_classification":"OFFICIAL_MANUAL_ACQUISITION_REQUIRED","machine_readable":True,"acquisition_mechanism":"official report interface","licence_status":"PUBLIC_ACCESS_TERMS_APPLY","redistribution_status":"LICENCE_RESTRICTIONS_UNKNOWN","raw_data_commit_allowed":False,"derived_data_commit_allowed":True,"usage_scope":"RESEARCH_ONLY","official_reference":"https://www.nseindia.com/all-reports","verification_date":"2026-10-04","research_profiles":["EXCHANGE_WIDE_PIT","INDEX_CONSTITUENT_PIT"],"readiness_gates":["prices","liquidity","reference"],"acquisition_status":"MANUAL_REQUEST_REQUIRED"},
    {"product_id":"NSE_CORPORATE_DATA","provider":"National Stock Exchange of India","product_name":"Corporate Data Subscription","dataset_purpose":"Corporate announcements, fundamentals and shareholding data","market_scope":"NSE listed issuers","historical_coverage_advertised":"EOD subscription; exact history subject to provider","granularity":"event/EOD","fields_advertised":["announcements","fundamentals","shareholding"],"delivery_format":"SFTP","source_classification":"OFFICIAL_SUBSCRIPTION_REQUIRED","machine_readable":True,"acquisition_mechanism":"official subscription","licence_status":"OFFICIAL_COMMERCIAL_LICENCE_REQUIRED","redistribution_status":"RESTRICTED","raw_data_commit_allowed":False,"derived_data_commit_allowed":False,"usage_scope":"LICENSE_TERMS_CONTROLLED_RESEARCH","official_reference":"https://betansearchives.nseindia.com/static/market-data/corporate-data-subscription","verification_date":"2026-10-04","research_profiles":["EXCHANGE_WIDE_PIT","INDEX_CONSTITUENT_PIT"],"readiness_gates":["corporate_actions","optional_fundamentals"],"acquisition_status":"SUBSCRIPTION_REQUIRED"},
    {"product_id":"NIFTY_HISTORICAL_CONSTITUENTS","provider":"NSE Indices Limited","product_name":"Historical constituent data subscription","dataset_purpose":"Authoritative historical index membership","market_scope":"NIFTY indices","historical_coverage_advertised":"Historical constituent data; coverage subject to product quote","granularity":"constituent snapshot/effective membership","fields_advertised":["index constituents","effective composition"],"delivery_format":"licensed data delivery","source_classification":"OFFICIAL_SUBSCRIPTION_REQUIRED","machine_readable":True,"acquisition_mechanism":"official data subscription/request","licence_status":"OFFICIAL_COMMERCIAL_LICENCE_REQUIRED","redistribution_status":"RESTRICTED","raw_data_commit_allowed":False,"derived_data_commit_allowed":False,"usage_scope":"LICENSE_TERMS_CONTROLLED_RESEARCH","official_reference":"https://www.niftyindices.com/offerings/data-subscription","verification_date":"2026-10-04","research_profiles":["INDEX_CONSTITUENT_PIT"],"readiness_gates":["index_membership","survivorship","universe"],"acquisition_status":"SUBSCRIPTION_REQUIRED"},
    {"product_id":"NIFTY_PRESS_RELEASE_ARCHIVE","provider":"NSE Indices Limited","product_name":"Index press release archive","dataset_purpose":"Official index reconstitution change notices","market_scope":"NIFTY indices","historical_coverage_advertised":"Historical notices, not proven complete continuous constituents","granularity":"change event","fields_advertised":["adds","removes","effective dates"],"delivery_format":"PDF","source_classification":"OFFICIAL_PUBLIC_VERIFIED","machine_readable":False,"acquisition_mechanism":"official public download","licence_status":"PUBLIC_ACCESS_TERMS_APPLY","redistribution_status":"LICENCE_RESTRICTIONS_UNKNOWN","raw_data_commit_allowed":False,"derived_data_commit_allowed":True,"usage_scope":"RESEARCH_ONLY","official_reference":"https://www.niftyindices.com/press-release","verification_date":"2026-10-04","research_profiles":["INDEX_CONSTITUENT_PIT"],"readiness_gates":["change_event_evidence_only"],"acquisition_status":"PUBLICLY_ACQUIRED"},
    {"product_id":"NIFTY_HISTORICAL_INDEX_PRICES","provider":"NSE Indices Limited","product_name":"Historical index data / reports","dataset_purpose":"Benchmark index prices","market_scope":"NIFTY indices","historical_coverage_advertised":"Historical index values by report","granularity":"daily","fields_advertised":["index values"],"delivery_format":"CSV/report","source_classification":"OFFICIAL_PUBLIC_VERIFIED","machine_readable":True,"acquisition_mechanism":"official report download","licence_status":"PUBLIC_ACCESS_TERMS_APPLY","redistribution_status":"LICENCE_RESTRICTIONS_UNKNOWN","raw_data_commit_allowed":False,"derived_data_commit_allowed":True,"usage_scope":"RESEARCH_ONLY","official_reference":"https://www.niftyindices.com/reports","verification_date":"2026-10-04","research_profiles":["INDEX_CONSTITUENT_PIT","EXCHANGE_WIDE_PIT"],"readiness_gates":["benchmark"],"acquisition_status":"MANUAL_REQUEST_REQUIRED"},
    {"product_id":"BSE_INFORMATION_PRODUCTS","provider":"BSE Limited","product_name":"Information Products - historical/EOD/reference/corporate data","dataset_purpose":"Alternative official market, reference, corporate action and historical trading data","market_scope":"BSE markets","historical_coverage_advertised":"Historical products available; exact coverage by product","granularity":"EOD/event/reference","fields_advertised":["EOD/reference","historical trading","corporate data","corporate actions"],"delivery_format":"licensed data delivery","source_classification":"OFFICIAL_SUBSCRIPTION_REQUIRED","machine_readable":True,"acquisition_mechanism":"official commercial product","licence_status":"OFFICIAL_COMMERCIAL_LICENCE_REQUIRED","redistribution_status":"RESTRICTED","raw_data_commit_allowed":False,"derived_data_commit_allowed":False,"usage_scope":"LICENSE_TERMS_CONTROLLED_RESEARCH","official_reference":"https://www.bseindia.com/downloads1/Information_Products_Pricing_Sheet.pdf","verification_date":"2026-10-04","research_profiles":["EXCHANGE_WIDE_PIT"],"readiness_gates":["secondary_exchange_reference","corporate_actions","prices"],"acquisition_status":"SUBSCRIPTION_REQUIRED"},
    {"product_id":"BSE_PUBLIC_CORPORATE_ACTIONS","provider":"BSE Limited","product_name":"Corporate Actions public interface","dataset_purpose":"Official corporate-action lookup","market_scope":"BSE listed issuers","historical_coverage_advertised":"Date-filtered public interface; complete coverage not established","granularity":"event","fields_advertised":["security","purpose","ex date","record date"],"delivery_format":"web/CSV","source_classification":"OFFICIAL_AUTOMATION_RESTRICTED","machine_readable":True,"acquisition_mechanism":"manual official interface/export","licence_status":"PUBLIC_ACCESS_TERMS_APPLY","redistribution_status":"LICENCE_RESTRICTIONS_UNKNOWN","raw_data_commit_allowed":False,"derived_data_commit_allowed":True,"usage_scope":"RESEARCH_ONLY","official_reference":"https://www.bseindia.com/corporates/corporates_act.html","verification_date":"2026-10-04","research_profiles":["EXCHANGE_WIDE_PIT"],"readiness_gates":["corporate_actions"],"acquisition_status":"AUTOMATION_RESTRICTED"},
    {"product_id":"BSE_PUBLIC_PRICE_HISTORY","provider":"BSE Limited","product_name":"Stock price historical interface","dataset_purpose":"Official historical security price lookup","market_scope":"BSE equity","historical_coverage_advertised":"User-selected history; bulk completeness not established","granularity":"daily","fields_advertised":["price history"],"delivery_format":"web report","source_classification":"OFFICIAL_MANUAL_ACQUISITION_REQUIRED","machine_readable":False,"acquisition_mechanism":"manual official interface","licence_status":"PUBLIC_ACCESS_TERMS_APPLY","redistribution_status":"LICENCE_RESTRICTIONS_UNKNOWN","raw_data_commit_allowed":False,"derived_data_commit_allowed":True,"usage_scope":"RESEARCH_ONLY","official_reference":"https://www.bseindia.com/markets/equity/EQReports/StockPrcHistori.aspx","verification_date":"2026-10-04","research_profiles":["EXCHANGE_WIDE_PIT"],"readiness_gates":["prices"],"acquisition_status":"MANUAL_REQUEST_REQUIRED"},
]
inventory = record("OFFICIAL_HISTORICAL_DATA_PRODUCT_INVENTORY_V1", {"verification_date":"2026-10-04","products":products,"official_sources_only":True})
save("official_historical_data_product_inventory_v1.json", inventory)

archives = [
    {"archive_id":"NSE_EQUITY_SECURITY_MASTER_20261003","source_id":"NSE_SECURITIES_MASTER","official_publisher":"National Stock Exchange of India","source_reference":"https://nsearchives.nseindia.com/content/equities/EQUITY_L.csv","original_filename":"EQUITY_L.csv","report_or_effective_date":"2026-10-03","retrieved_at":"2026-10-03T00:00:00Z","byte_length":183140,"sha256":"95f0d731f5858f71e876c45377dcefa79bc7a8db1e8161d0c92320252af4aa8f","local_relative_storage_path":"data/raw/nse/EQUITY_L.csv","licence_classification":"OFFICIAL_PUBLIC_VERIFIED","redistribution_status":"LICENCE_RESTRICTIONS_UNKNOWN","raw_data_commit_allowed":False,"derived_data_commit_allowed":True,"usage_scope":"RESEARCH_ONLY","raw_file_committed":False,"coverage":"CURRENT_SNAPSHOT_ONLY","record_count":2593},
    {"archive_id":"NSE_DELISTED_COMPANIES_20260910","source_id":"NSE_DELISTINGS","official_publisher":"National Stock Exchange of India","source_reference":"https://nsearchives.nseindia.com/web/mediaattachment/2026-09/Copy_of_List_of_delisted_Companies_20260612152719_9_20260901172525_1_20260910122051.xlsx","original_filename":"NSE_delisted_companies_20260910.xlsx","report_or_effective_date":"2026-09-10","retrieved_at":"2026-10-03T00:00:00Z","byte_length":61796,"sha256":"fcc27d5850f381fa0193003ddbd4d2f7724c770e9082d7fbbad6b97dd87f1664","local_relative_storage_path":"data/raw/nse/NSE_delisted_companies_20260910.xlsx","licence_classification":"OFFICIAL_PUBLIC_VERIFIED","redistribution_status":"LICENCE_RESTRICTIONS_UNKNOWN","raw_data_commit_allowed":False,"derived_data_commit_allowed":True,"usage_scope":"RESEARCH_ONLY","raw_file_committed":False,"coverage":"2002-04-15..2026-09-02","record_count":457},
    {"archive_id":"NIFTY_50_CHANGE_20200218","source_id":"NIFTY_PRESS_RELEASE_ARCHIVE","official_publisher":"NSE Indices Limited","source_reference":"https://www.niftyindices.com/Press_Release/ind_prs18022020.pdf","original_filename":"ind_prs18022020.pdf","report_or_effective_date":"2020-02-18","retrieved_at":"2026-10-04T00:00:00Z","byte_length":None,"sha256":"1943215214a0b967333ae4ec9c6aeaec9c5012fb03558c769ad895b7d1081f9e","local_relative_storage_path":"data/raw/historical/ind_prs18022020.pdf","licence_classification":"OFFICIAL_PUBLIC_VERIFIED","redistribution_status":"LICENCE_RESTRICTIONS_UNKNOWN","raw_data_commit_allowed":False,"derived_data_commit_allowed":True,"usage_scope":"RESEARCH_ONLY","raw_file_committed":False,"coverage":"CHANGE_EVENT_ONLY"},
    {"archive_id":"NIFTY_50_CHANGE_20200820","source_id":"NIFTY_PRESS_RELEASE_ARCHIVE","official_publisher":"NSE Indices Limited","source_reference":"https://www.niftyindices.com/Press_Release/ind_prs20082020.pdf","original_filename":"ind_prs20082020.pdf","report_or_effective_date":"2020-08-20","retrieved_at":"2026-10-04T00:00:00Z","byte_length":None,"sha256":"46c98f2c6cc53f925bed74bface526afc752a39706828836be23ab38d1fa898c","local_relative_storage_path":"data/raw/historical/ind_prs20082020.pdf","licence_classification":"OFFICIAL_PUBLIC_VERIFIED","redistribution_status":"LICENCE_RESTRICTIONS_UNKNOWN","raw_data_commit_allowed":False,"derived_data_commit_allowed":True,"usage_scope":"RESEARCH_ONLY","raw_file_committed":False,"coverage":"CHANGE_EVENT_ONLY"},
]
save("authoritative_data_archive_manifest_v1.json", record("AUTHORITATIVE_DATA_ARCHIVE_MANIFEST_V1", {"retrieval_policy":"OFFICIAL_DOMAIN_NO_BYPASS","raw_files_committed":False,"archives":archives}))

requirements = record("OFFICIAL_DATA_ACQUISITION_REQUIREMENTS_V1", {"requirements":[
    {"requirement_id":"REQ_NIFTY_BROAD_CONSTITUENTS","exact_dataset":"Historical constituent data for NIFTY 500 (preferred) or NIFTY 200","provider":"NSE Indices Limited","research_purpose":"Bounded broad cross-sectional PIT universe","preferred_date_coverage":"2016-01-01..2026-10-03","minimum_acceptable_date_coverage":"Any continuous verified multi-year period ending no later than 2026-10-03","required_fields":["index ID","effective/snapshot date","ISIN","symbol","company"],"preferred_file_format":"CSV","target_research_profile":"INDEX_CONSTITUENT_PIT","readiness_gate":"index_membership_and_universe","one_time_historical_purchase_may_suffice":True,"ongoing_subscription_required":False,"ingestion_adapter_status":"IMPLEMENTED_OFFLINE","expected_local_destination":"data/external_authoritative/nifty_constituents/","validation_steps":["hash raw bytes","validate exact schema","build bounded periods","measure gaps","run V3"]},
    {"requirement_id":"REQ_NSE_CM_EOD","exact_dataset":"NSE Capital Market EOD/Historical security, bhavcopy and trade-detail data","provider":"National Stock Exchange of India","research_purpose":"Official prices, liquidity, trading status and security reference","preferred_date_coverage":"2016-01-01..2026-10-03","minimum_acceptable_date_coverage":"Same continuous period as selected universe","required_fields":["date","ISIN/security ID","symbol","series","OHLC","volume","turnover","trading status"],"preferred_file_format":"CSV or documented fixed format","target_research_profile":"BOTH","readiness_gate":"market_data_identity_liquidity","one_time_historical_purchase_may_suffice":True,"ongoing_subscription_required":False,"ingestion_adapter_status":"SECURITY_MASTER_IMPLEMENTED_EOD_PRICE_LAYOUT_REQUIRES_DELIVERY_SPEC","expected_local_destination":"data/external_authoritative/nse_historical_eod/","validation_steps":["hash raw bytes","bind delivery specification","validate adjustment semantics","audit sessions","run V3"]},
    {"requirement_id":"REQ_NSE_CORPORATE_ACTIONS","exact_dataset":"Official effective-dated corporate actions for selected period","provider":"National Stock Exchange of India","research_purpose":"Price adjustment and identity/event correctness","preferred_date_coverage":"2016-01-01..2026-10-03","minimum_acceptable_date_coverage":"Same continuous period as selected universe","required_fields":["ISIN","symbol","action type","record date","ex/effective date","terms"],"preferred_file_format":"CSV","target_research_profile":"BOTH","readiness_gate":"corporate_action_adjustment","one_time_historical_purchase_may_suffice":True,"ongoing_subscription_required":False,"ingestion_adapter_status":"IMPLEMENTED_OFFLINE","expected_local_destination":"data/external_authoritative/nse_corporate_actions/","validation_steps":["hash raw bytes","validate effective dates","reject unknown action schema","audit adjustment policy"]}
]})
save("official_data_acquisition_requirements_v1.json", requirements)

purchase = record("MINIMUM_DATA_PURCHASE_PLAN_V1", {"recommendation":"ONE_TIME_HISTORICAL_CONSTITUENT_DATA_REQUIRED","preferred_first_profile":"INDEX_CONSTITUENT_PIT","preferred_universe":"NIFTY_500","acceptable_fallback":"NIFTY_200 if coverage/licence is materially more obtainable","minimum_actions":["Obtain one-time authoritative broad-index constituent history for a continuous bounded period","Establish official NSE EOD/security coverage for the identical period; purchase only if public official archive cannot be legitimately completed","Obtain matching corporate-action history if EOD delivery does not include adjustment/reference support"],"ongoing_subscription_required_for_retrospective_research":False,"exact_price_estimate":None,"price_note":"No price estimate asserted; request current official quote/terms.","exchange_wide_purchase_deferred":True,"rationale":"A broad official index history is the lowest-scope route to a defensible cross-sectional PIT universe; full exchange-wide master history is not required for the first bounded challenger."})
save("minimum_data_purchase_plan_v1.json", purchase)

policy = {"policy_id":"SURVIVORSHIP_COVERAGE_POLICY_V1","classification":"RESEARCH_GOVERNANCE_THRESHOLD","thresholds":{"maximum_unknown_universe_share":0.02,"minimum_security_identity_coverage":0.99,"minimum_known_non_survivors":1,"minimum_evidence_source_count":2,"minimum_continuous_years":3,"delisting_coverage_required":True},"scientific_truth_claimed":False,"change_control":"Version and reapprove; never mutate silently."}
policy["canonical_hash"] = sha256(policy)
save("survivorship_coverage_policy_v1.json", policy)

market = market_data_readiness(ohlc=True, volume=True, turnover=False, trading_days=True, adjustment_state="UNKNOWN", official_provenance=False)
market.update({"current_assessment":"Existing frozen Stage 4 data is not replaced; NextGen official turnover, adjustment and complete provenance remain unverified.","official_nse_eod_would_materially_improve":["price provenance","liquidity modeling","corporate-action correctness","suspended/untraded detection"]})
save("market_data_source_readiness_v1.json", market)

adjustment = record("NEXTGEN_PRICE_ADJUSTMENT_POLICY_V1", {"allowed_states":["RAW_UNADJUSTED","SPLIT_ADJUSTED","DIVIDEND_ADJUSTED","TOTAL_RETURN_ADJUSTED"],"unknown_state_action":"REJECT_FOR_RETURN_FEATURES","mixing_states_permitted":False,"raw_price_retention_required":True,"corporate_action_provenance_required":True,"dividend_treatment_must_be_explicit":True,"current_state":"NOT_VERIFIED","model_training_permitted":False})
save("nextgen_price_adjustment_policy_v1.json", adjustment)

features = feature_pit_readiness([
    {"family":"technical","status":"REQUIRES_NEW_SOURCE","required_for_minimal_profile":True,"reason":"Official bounded price history not yet ingested"},
    {"family":"momentum","status":"REQUIRES_NEW_SOURCE","required_for_minimal_profile":True,"reason":"Official bounded adjusted/raw semantics absent"},
    {"family":"volatility","status":"REQUIRES_NEW_SOURCE","required_for_minimal_profile":True,"reason":"Official bounded OHLC history absent"},
    {"family":"liquidity","status":"REQUIRES_NEW_SOURCE","required_for_minimal_profile":True,"reason":"Turnover and untraded-session completeness absent"},
    {"family":"market_index","status":"REQUIRES_EFFECTIVE_DATE_LOGIC","required_for_minimal_profile":True,"reason":"Benchmark series must be bound to session dates"},
    {"family":"fundamentals","status":"OPTIONAL_FUTURE_FEATURE_FAMILY","required_for_minimal_profile":False,"reason":"Not required for first technical/liquidity challenger"},
    {"family":"stage6_events","status":"PIT_SAFE_NOW","required_for_minimal_profile":False,"reason":"Use only immutable observed-at evidence from frozen Stage 6 contracts"},
])
save("nextgen_feature_pit_readiness_v1.json", features)

v1_hash = file_sha256(ROOT/"results/advanced_research_readiness_v1.json")
v2_hash = file_sha256(ROOT/"results/advanced_research_readiness_v2.json")
closed = {"gates":{"universe":False,"identity":False,"survivorship":False,"market_data":False,"costs":True,"benchmark":True,"features":False},"period":None,"source_manifests":["AUTHORITATIVE_DATA_ARCHIVE_MANIFEST_V1"],"security_coverage":"CURRENT_SNAPSHOT_ONLY","identity_coverage":"PARTIAL","survivorship_assessment":"INSUFFICIENT"}
index_closed = {**closed,"gates":{**closed["gates"],"index_membership":False},"security_coverage":"CHANGE_EVENTS_ONLY"}
v3 = readiness_v3(profiles={"EXCHANGE_WIDE_PIT":closed,"INDEX_CONSTITUENT_PIT":index_closed},v1_hash=v1_hash,v2_hash=v2_hash)
save("advanced_research_readiness_v3.json", v3)

decision = record("NEXTGEN_DATA_ACQUISITION_DECISION_V1", {"exchange_wide_public_official_sufficient":"PARTIAL","index_constituent_public_official_sufficient":"PARTIAL","missing_official_products":["NSE Indices historical broad-index constituent data","NSE Capital Market historical EOD/security data if public archive cannot cover chosen period","matching official corporate actions"],"minimum_acquisition":"ONE_TIME_HISTORICAL_CONSTITUENT_DATA_REQUIRED","period_unlocked":"Exact period depends on delivered licensed coverage; preferred 2016-01-01..2026-10-03, minimum continuous multi-year period","simple_challenger_sufficient_after_all_gates":True,"stockmixer_cross_stock_note":"Still requires a broader, sufficiently large, continuously verified cross-section and is explicitly out of scope until simple baselines justify it.","public_data_limit":"Current master, delistings and change notices are valuable evidence but do not establish a complete continuous PIT universe.","purchase_or_contact_performed":False})
save("nextgen_data_acquisition_decision_v1.json", decision)

contract = {"contract_id":"NEXTGEN_AUTHORITATIVE_DATA_CONTRACT_V1","result":"PASS_FAIL_CLOSED","branch":"nextgen-research-authoritative-data","parent_commit":"986f9e6cae2574246fa56ec8f7084addc8bcc58b","research_period":"2016-01-01..2026-10-03","v1_sha256":v1_hash,"v2_sha256":v2_hash,"v3_status":v3["status"],"v3_reason":v3["reason"],"public_archives_recorded":len(archives),"products_investigated":len(products),"raw_files_committed":0,"fixture_only_tests":True,"network_calls_in_tests":0,"model_training":False,"trading_authority":False,"tags_created":0,"regressions":{"focused":"83/83 PASS","readiness_v2":"22/22 PASS","historical_evidence":"63/63 PASS","real_data":"58/58 PASS","nextgen_foundation":"104/104 PASS","stage6_8c":"170/170 PASS","stage5d":"606/606 PASS","stage6_0c":"PASS / 10 schemas","full_stage6":"FROZEN_TEST_HARNESS_BRANCH_CONSTRAINT"}}
contract["artifact_hashes"]={name:file_sha256(ROOT/"results"/name) for name in ["official_historical_data_product_inventory_v1.json","authoritative_data_archive_manifest_v1.json","official_data_acquisition_requirements_v1.json","minimum_data_purchase_plan_v1.json","survivorship_coverage_policy_v1.json","market_data_source_readiness_v1.json","nextgen_price_adjustment_policy_v1.json","nextgen_feature_pit_readiness_v1.json","advanced_research_readiness_v3.json","nextgen_data_acquisition_decision_v1.json"]}
save("nextgen_authoritative_data_contract.json", contract)
print(json.dumps({"status":"PASS","products":len(products),"archives":len(archives),"v3":v3["status"]},sort_keys=True))
