from copy import deepcopy

from stage6_ingestion.canonical import canonical_hash, utc_timestamp, without
from .fill_math import aggregate_fills, canonicalize_fills
from .policy import *

SAFETY={
"recommendation_source_status":"FROZEN","fill_source_status":"FROZEN","supporting_evidence_status":"FROZEN","initial_thesis_semantics_status":"FROZEN","trade_thesis_v2_status":"NOT_MATERIALIZED","thesis_review_status":"NOT_EVALUATED","dynamic_management_status":"NOT_EVALUATED","portfolio_interaction_status":"NOT_EVALUATED","buy_sell_hold_status":"NOT_EVALUATED","trading_authority":False,"network_calls":0,"external_api_calls":0,"stage5d_live_database_calls":0,"broker_calls":0,"market_data_downloads":0,"llm":False,"nlp":False,"ml":False,"ocr":False,"embeddings":False,"semantic_similarity":False}

def build_seed(source,evidence_bindings,policy_hash,seed_contract_hash):
    source=deepcopy(source); fills=canonicalize_fills(source["fills"])
    aggregate,entry_date=aggregate_fills(fills)
    projected=[{k:x[k] for k in ("transaction_id","fill_date","quantity","price","currency","source_system")} for x in fills]
    semantic={"semantic_projection_version":SEMANTIC_PROJECTION_VERSION,"version":1,"decision_cutoff":utc_timestamp(source["decision_cutoff"],"decision_cutoff"),"recommendation_id":source["recommendation_id"],"ticker":source["ticker"],"derived_entry_date":entry_date,"holding_horizon":source["holding_horizon"],"entry_rationale":source["entry_rationale"],"supporting_evidence_ids":source["supporting_evidence_ids"],"known_risks":source["known_risks"],"initial_entry_range":source["initial_entry_range"],"projected_fill_references":projected,"aggregate_fill":aggregate,"initial_stop":source["initial_stop"],"current_stop":source["initial_stop"],"initial_target":source["initial_target"],"current_target":source["initial_target"],"invalidation_conditions":source["invalidation_conditions"],"thesis_status":"THESIS_UNCHANGED","last_review_date":utc_timestamp(source["decision_cutoff"],"decision_cutoff")[:10],"previous_version_hash":None,"initial_change_semantics":{"version":1,"change_type":"INITIAL_THESIS_CREATED","reason":"INITIAL_BASELINE_FROM_IMMUTABLE_SEED","changed_at_semantic":utc_timestamp(source["decision_cutoff"],"decision_cutoff"),"evidence_ids":source["supporting_evidence_ids"]}}
    record={"schema_version":SCHEMA_VERSION,"seed_record_id":"","source_system":source["source_system"],"source_stage5d5_commit":source["source_stage5d5_commit"],"source_export_id":source["source_export_id"],"source_export_hash":source["source_export_hash"],"source_database_id":source["source_database_id"],"source_schema_version":source["source_schema_version"],"decision_cutoff":utc_timestamp(source["decision_cutoff"],"decision_cutoff"),"recommendation_binding":source["recommendation_binding"],"recommendation_id":source["recommendation_id"],"ticker":source["ticker"],"holding_horizon":source["holding_horizon"],"entry_rationale":source["entry_rationale"],"known_risks":source["known_risks"],"initial_entry_range":source["initial_entry_range"],"original_fill_audit_records":fills,"projected_fill_references":projected,"aggregate_fill":aggregate,"derived_entry_date":entry_date,"initial_stop":source["initial_stop"],"initial_target":source["initial_target"],"invalidation_conditions":source["invalidation_conditions"],"supporting_evidence_ids":source["supporting_evidence_ids"],"evidence_bindings":evidence_bindings,"initial_thesis_semantic_projection":semantic,"policy_id":POLICY_ID,"policy_hash":policy_hash,"seed_contract_version":SEED_CONTRACT_VERSION,"seed_contract_hash":seed_contract_hash,"processor_version":PROCESSOR_VERSION,"authority":AUTHORITY,**SAFETY,"record_hash":""}
    record["seed_record_id"]="S6THSEED_"+canonical_hash(without(record,"seed_record_id","record_hash"))[:24]
    record["record_hash"]=canonical_hash(without(record,"record_hash"))
    return record
