from stage6_ingestion.canonical import canonical_hash,without
SCHEMA_VERSION="STAGE6_EVENT_DIMENSION_MOVEMENT_V1"
def movement_item_id(match,event,item,policy_hash,processor):return "S6MOVITEM_"+canonical_hash({"match_id":match["match_id"],"match_hash":match["record_hash"],"event_id":event["event_id"],"event_version":event["event_version"],"event_hash":event["record_hash"],"movement_rule_id":item["movement_rule_id"],"movement_rule_hash":item["movement_rule_hash"],"source_event_qualifier_id":item["source_event_qualifier_id"],"source_dimension_entity_id":item["source_dimension_entity_id"],"reference_event_qualifier_id":item["reference_event_qualifier_id"],"reference_dimension_entity_id":item["reference_dimension_entity_id"],"movement_metric":item["movement_metric"],"movement_direction":item["movement_direction"],"evidence_refs":item["evidence_refs"],"policy_hash":policy_hash,"processor_version":processor})[:24]
def movement_record_id(match,items,policy_hash,processor):return "S6MOV_"+canonical_hash({"schema_version":SCHEMA_VERSION,"match_id":match["match_id"],"match_hash":match["record_hash"],"movement_items":items,"policy_id":"S6MOVPOL_STAGE6_3G_V1","policy_hash":policy_hash,"processor_version":processor})[:24]
def eligible_subjects(match,event_type,rules):
 rule=rules.get(event_type)
 if rule is None:return []
 entities={e for p in match["path_matches"] if p["source_rule_id"]==rule["source_rule_id"] and p["dimension_match_status"]=="EXACT_ENTITY_MATCH" for e in p["matched_dimension_entity_ids"]}
 return sorted(q["event_qualifier_id"] for q in match["event_qualifiers"] if q["dimension_type"]==rule["dimension_type"] and q["dimension_entity_id"] in entities)
def build_event_movement(*,match,event,event_registry,movement_items,policy,policy_hash):
 rules={x["event_type"]:x for x in policy["rules"]};items=sorted(movement_items,key=lambda x:(x["source_event_qualifier_id"],x["reference_event_qualifier_id"] or "",x["movement_metric"],x["movement_direction"]));items=[{"movement_item_id":movement_item_id(match,event,x,policy_hash,policy["processor_version"]),**x} for x in items];eligible=eligible_subjects(match,event["event_type"],rules);qualified=sorted({x["source_event_qualifier_id"] for x in items});unqualified=sorted(set(eligible)-set(qualified));status="NO_ELIGIBLE_MOVEMENT_TARGETS" if not eligible else "UNQUALIFIED" if not qualified else "PARTIALLY_QUALIFIED" if unqualified else "ALL_ELIGIBLE_SUBJECTS_QUALIFIED"
 out={"schema_version":SCHEMA_VERSION,"movement_record_id":"","record_hash":"0"*64,"match_id":match["match_id"],"match_hash":match["record_hash"],"event_id":event["event_id"],"event_version":event["event_version"],"event_hash":event["record_hash"],"event_type":event["event_type"],"event_entity_registry_snapshot_id":event_registry["registry_snapshot_id"],"event_entity_registry_version":event_registry["registry_version"],"event_entity_registry_hash":event_registry["registry_hash"],"movement_cutoff_timestamp":match["match_cutoff_timestamp"],"movement_scope":"EVENT_DIMENSION_ONLY","eligible_subject_event_qualifier_ids":eligible,"qualified_subject_event_qualifier_ids":qualified,"unqualified_eligible_subject_event_qualifier_ids":unqualified,"movement_qualification_status":status,"movement_items":items,"aggregate_event_movement_status":"NOT_EVALUATED","path_effect_direction_status":"NOT_EVALUATED","overall_company_effect_status":"NOT_EVALUATED","stock_direction_status":"NOT_EVALUATED","market_reaction_status":"NOT_EVALUATED","magnitude_status":"NOT_EVALUATED","expected_return_status":"NOT_EVALUATED","policy_id":policy["policy_id"],"policy_hash":policy_hash,"processor_version":policy["processor_version"],"authority":policy["authority"]};out["movement_record_id"]=movement_record_id(match,items,policy_hash,policy["processor_version"]);out["record_hash"]=canonical_hash(without(out,"record_hash"));return out
