import ast,csv,hashlib,json,sqlite3,subprocess,sys,tempfile
from copy import deepcopy
from datetime import datetime,timezone
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];REPO=ROOT.parent;sys.path.insert(0,str(ROOT))
from stage6_ingestion.canonical import canonical_hash,canonical_json,without
from stage6_prospective_validation.errors import *
from stage6_prospective_validation.policy import *
from stage6_prospective_validation.protocol import verify_configuration
import stage6_prospective_validation.activation as activation
from stage6_prospective_validation.control_reader import Stage5DControlReader,canonical_json as cjson,payload_sha256
from stage6_prospective_validation.stage6_shadow_reader import Stage6ShadowReader,ORIGIN_SCHEMA,create_runtime_origin_marker
from stage6_prospective_validation.enrollment_builder import SAFETY,build_session,build_submission,build_case
from stage6_prospective_validation.enrollment_validation import validate_run_eligibility,validate_pairing
from stage6_prospective_validation.prospective_store import TABLES,ProspectiveValidationStore

OUT=ROOT/"results/stage6_8a_test_results.csv";CASES=[];CTX={}
def case(group,name,fn):CASES.append((group,name,fn))
def require(value,message="assertion failed"):
 if not value:raise AssertionError(message)
def expect(error,fn):
 try:fn()
 except error:return
 raise AssertionError("expected error")
def git(*args):return subprocess.check_output(["git",f"--git-dir={REPO/'_git'}",f"--work-tree={REPO}",*args],cwd=REPO,text=True).strip()
def result_count(stage):
 rows=list(csv.DictReader((ROOT/"results"/f"stage6_{stage}_test_results.csv").open(encoding="utf-8")));require(all(x["result"]=="PASS" for x in rows));return len(rows)
def prior_count():return sum(result_count(x) for x in ("1a","1b","1c","2a","2b","2c","2d","2e","2f","3a","3b","3c","3d","3e","3f","3g","3h","3i","4a","4b","4c","4d","4e","5a","5b","5c","5d","6a","6b","6c","6d","6e","6f","6g","7a","7b"))
def file_hash(path):return hashlib.sha256(Path(path).read_bytes()).hexdigest()

for name,actual,wanted in (("protocol",PROTOCOL_ID,"STAGE6_PROSPECTIVE_VALIDATION_PROTOCOL_V1"),("activation",ACTIVATION_SCHEMA,"STAGE6_PROSPECTIVE_ACTIVATION_V1"),("session",SESSION_SCHEMA,"STAGE6_PROSPECTIVE_SESSION_ENROLLMENT_V1"),("case",CASE_SCHEMA,"STAGE6_PROSPECTIVE_CASE_ENROLLMENT_V1"),("store",STORE_SCHEMA,"STAGE6_8A_PROSPECTIVE_VALIDATION_STORE_V1"),("processor",PROCESSOR,"STAGE6_8A_PROSPECTIVE_VALIDATION_ENROLLER_V1"),("policy",POLICY_ID,"S6PROSVALPOL_STAGE6_8A_V1"),("contract",CONTRACT_VERSION,"STAGE6_PROSPECTIVE_VALIDATION_ENROLLMENT_CONTRACT_V1"),("authority",AUTHORITY,"SHADOW_ONLY"),("component",COMPONENT,"MORNING_REVALIDATION_V1")):case("IDENTITY",name,lambda actual=actual,wanted=wanted:require(actual==wanted))
case("BASELINE","branch",lambda:require(git("branch","--show-current")==BRANCH));case("BASELINE","closure",lambda:require(git("merge-base","HEAD",BASELINE)==BASELINE));case("BASELINE","parent",lambda:require(git("rev-parse",f"{BASELINE}^")=="66c6b7bdbc2fb3dd993e6a2900215a74d5f3c415"));case("BASELINE","7B",lambda:require(result_count("7b")==353));case("BASELINE","prior",lambda:require(prior_count()-353==4620));case("BASELINE","combined",lambda:require(prior_count()==4973));case("BASELINE","closure status",lambda:require("COMPLETE_SHADOW_ONLY" in (ROOT/"Stage6_7_Closure_Report.md").read_text()))
case("CONTROL_FREEZE","tag",lambda:require(git("rev-list","-n","1",CONTROL_TAG)==CONTROL_COMMIT));case("CONTROL_FREEZE","subtree",lambda:require(subprocess.run(["git",f"--git-dir={REPO/'_git'}",f"--work-tree={REPO}","diff","--quiet",CONTROL_COMMIT,"HEAD","--","Stage 5D"]).returncode==0))
case("CONFIG","protocol hash",lambda:require(load_protocol()[2]==EXPECTED_PROTOCOL_HASH));case("CONFIG","policy hash",lambda:require(load_policy()[2]==EXPECTED_POLICY_HASH));case("CONFIG","contract hash",lambda:require(load_contract()[2]==EXPECTED_CONTRACT_HASH));case("CONFIG","verify",lambda:require(verify_configuration()["result"]=="PASS"));case("PROTOCOL","window 20",lambda:require(MINIMUM_SESSIONS==20));case("PROTOCOL","not promotion",lambda:require(load_protocol()[0]["minimum_window_is_promotion_threshold"] is False));case("PROTOCOL","early stop",lambda:require(load_protocol()[0]["performance_based_early_stopping"]=="PROHIBITED"));case("PROTOCOL","zero candidates",lambda:require(load_protocol()[0]["zero_candidate_sessions_count"]));case("PROTOCOL","zero recommendations",lambda:require(load_protocol()[0]["zero_recommendation_sessions_count"]));case("PROTOCOL","missing preserved",lambda:require(load_protocol()[0]["missing_shadow_output"]=="PRESERVE_AS_VALIDATION_EVIDENCE"))
for state in sorted(CASE_STATES):case("CASE_STATE",state,lambda state=state:require(state in CASE_STATES))
case("ACTIVATION","temp created",lambda:require(CTX["activation"]["schema_version"]==ACTIVATION_SCHEMA));case("ACTIVATION","content id",lambda:require(CTX["activation"]["activation_id"]=="S6PROSACT_"+canonical_hash(without(CTX["activation"],"activation_id","record_hash"))[:24]));case("ACTIVATION","hash",lambda:require(CTX["activation"]["record_hash"]==canonical_hash(without(CTX["activation"],"record_hash"))));case("ACTIVATION","UTC internal",lambda:require(CTX["activation"]["activated_at_utc"]=="2026-09-30T10:00:00Z"));case("ACTIVATION","IST date",lambda:require(CTX["activation"]["activation_date_ist"]=="2026-09-30"));case("ACTIVATION","one only",lambda:expect(ActivationBlocked,CTX["reactivate"]));case("ACTIVATION","status active",lambda:require(activation.activation_status(CTX["activation_dir"])["status"]=="ACTIVE"));case("ACTIVATION","status absent",lambda:require(activation.activation_status(CTX["absent_dir"])["status"]=="NOT_ACTIVATED"));case("ACTIVATION","real absent",lambda:require(not (ROOT/"runtime/prospective_validation/activation_record.json").exists()));case("ACTIVATION","help",lambda:require("Activate the audited" in subprocess.check_output([sys.executable,"-m","stage6_prospective_validation.activation","--help"],text=True)))
case("CONTROL","query only",lambda:require(CTX["control_query_only"]));case("CONTROL","integrity",lambda:require(CTX["control_result"]=="PASS"));case("CONTROL","file unchanged",lambda:require(CTX["control_before"]==file_hash(CTX["control_db"])));case("CONTROL","schema unchanged",lambda:require(CTX["control_schema_before"]==CTX["control_schema_after"]));case("CONTROL","rows unchanged",lambda:require(CTX["control_rows_before"]==CTX["control_rows_after"]));
for operation in ("CREATE TABLE forbidden(x)","INSERT INTO stage5d5_meta VALUES(2,'X')","UPDATE stage5d5_meta SET schema_version='X'","DELETE FROM stage5d5_meta"):case("CONTROL_READ_ONLY",operation.split()[0],lambda operation=operation:expect(sqlite3.OperationalError,lambda:CTX["control"].connection.execute(operation)))
case("SESSION","zero created",lambda:require(CTX["session0"]["zero_candidate_flag"] and CTX["session0"]["zero_recommendation_flag"]));case("SESSION","ordinal one",lambda:require(CTX["session0"]["session_ordinal_since_activation"]==1));case("SESSION","ordinal two",lambda:require(CTX["session1"]["session_ordinal_since_activation"]==2));case("SESSION","id deterministic",lambda:require(CTX["session1"]["enrollment_id"].startswith("S6PROSSESS_")));case("SESSION","hash",lambda:require(CTX["session1"]["record_hash"]==canonical_hash(without(CTX["session1"],"record_hash"))));case("SESSION","idempotent",lambda:require(CTX["session_replay"]=="IDEMPOTENT_SUCCESS"));case("SESSION","out of order",lambda:expect(Stage6ProspectiveError,CTX["out_of_order"]));
for key in ("candidate_count","recommendation_count","news_status","allocation_run_id","management_session_run_id","stage4a3_snapshot_id","market_data_hash","candidate_input_hash"):case("SESSION_COPY",key,lambda key=key:require(CTX["session1"][key]==CTX["run1"][key]))
case("CHRONOLOGY","same day reject",lambda:expect(Stage6ProspectiveError,lambda:validate_run_eligibility(CTX["activation"],{**CTX["run1"],"market_session_date":"2026-09-30"})));case("CHRONOLOGY","prior reject",lambda:expect(Stage6ProspectiveError,lambda:validate_run_eligibility(CTX["activation"],{**CTX["run1"],"market_session_date":"2026-09-29"})));case("CHRONOLOGY","started reject",lambda:expect(Stage6ProspectiveError,lambda:validate_run_eligibility(CTX["activation"],{**CTX["run1"],"run_started_utc":"2026-09-30T09:00:00Z"})));case("CHRONOLOGY","completed reject",lambda:expect(Stage6ProspectiveError,lambda:validate_run_eligibility(CTX["activation"],{**CTX["run1"],"run_completed_utc":"2026-10-02T07:00:00Z"})))
case("CASE","control only",lambda:require(CTX["control_case"]["case_state"]=="CONTROL_ONLY_PENDING_SHADOW"));case("CASE","paired",lambda:require(CTX["paired_case"]["case_state"]=="PAIRED_SHADOW_AVAILABLE"));case("CASE","outcome",lambda:require(CTX["control_case"]["outcome_status"]=="NOT_ATTACHED" and CTX["paired_case"]["outcome_status"]=="NOT_ATTACHED"));case("CASE","replay",lambda:require(CTX["case_replay"]=="IDEMPOTENT_SUCCESS"));case("CASE","recommendation",lambda:require(CTX["paired_case"]["recommendation_id"]=="REC2"));case("CASE","ticker",lambda:require(CTX["paired_case"]["ticker"]=="AAA.NS"));case("CASE","horizon",lambda:require(CTX["paired_case"]["selected_horizon"]=="SWING"));case("CASE","pending",lambda:require(CTX["paired_case"]["pending_entry_event_binding"]["record_id"]=="EVT2"));case("CASE","submission",lambda:require(CTX["paired_case"]["shadow_submission_binding"] is not None));case("CASE","deps control",lambda:require(len(CTX["control_case"]["direct_dependencies"])==5));case("CASE","deps paired",lambda:require(len(CTX["paired_case"]["direct_dependencies"])==6));case("CASE","missing not excluded",lambda:require("SHADOW_OUTPUT_MISSING" in CASE_STATES and CTX["control_case"]["shadow_availability"]=="NOT_SUBMITTED"))
case("SHADOW","query only",lambda:require(CTX["shadow_query_only"]));case("SHADOW","submission internal",lambda:require(CTX["submission"]["submitted_at_utc"]));case("SHADOW","target",lambda:require(CTX["submission"]["target_session_date"]=="2026-10-02"));case("SHADOW","decision",lambda:require(CTX["submission"]["proposal_decision"]=="WAIT"));case("SHADOW","hash",lambda:require(CTX["submission"]["record_hash"]==canonical_hash(without(CTX["submission"],"record_hash"))));case("SHADOW","fixture rejected",lambda:expect(Stage6ProspectiveError,lambda:Stage6ShadowReader(CTX["shadow_db"],ROOT/"fixtures",CTX["activation"])));case("SHADOW","pair mismatch",lambda:expect(Stage6ProspectiveError,lambda:validate_pairing(CTX["activation"],CTX["session1"],CTX["rec2"],{**CTX["proposal"],"ticker":"OTHER"},"2026-10-02T08:30:00Z")))
for key,value in SAFETY.items():case("SAFETY",key,lambda key=key,value=value:require(CTX["paired_case"][key]==value))
case("STORE","integrity",lambda:require(CTX["store"].integrity_check()["result"]=="PASS"));case("STORE","restart",lambda:require(CTX["restart"]()=="PASS"));case("STORE","trigger loss",lambda:expect(Exception,CTX["trigger_loss"]));
for table in TABLES:
 case("APPEND",table+" update",lambda table=table:expect(sqlite3.DatabaseError,lambda:CTX["store"].connection.execute(f"UPDATE {table} SET rowid=rowid")))
 case("APPEND",table+" delete",lambda table=table:expect(sqlite3.DatabaseError,lambda:CTX["store"].connection.execute(f"DELETE FROM {table}")))
for table,stmt in (("prospective_sessions","UPDATE prospective_sessions SET record_hash='bad'"),("prospective_control_recommendations","UPDATE prospective_control_recommendations SET payload_sha256='bad'"),("prospective_pending_events","UPDATE prospective_pending_events SET payload_sha256='bad'"),("prospective_shadow_submissions","UPDATE prospective_shadow_submissions SET record_hash='bad'"),("prospective_cases","UPDATE prospective_cases SET record_hash='bad'"),("prospective_case_dependencies","UPDATE prospective_case_dependencies SET record_hash='bad'"),("prospective_audits","UPDATE prospective_audits SET canonical_json='{}'"),("prospective_protocols","UPDATE prospective_protocols SET protocol_hash='bad'"),("prospective_policies","UPDATE prospective_policies SET policy_hash='bad'"),("prospective_contracts","UPDATE prospective_contracts SET contract_hash='bad'"),("prospective_activations","UPDATE prospective_activations SET record_hash='bad'")):
 case("TAMPER",table,lambda table=table,stmt=stmt:expect(Exception,lambda:CTX["tamper"](table,stmt)))
case("RUNTIME","gitignore",lambda:require((ROOT/"runtime/prospective_validation/.gitignore").read_text()=="*\n!.gitignore\n"));case("RUNTIME","no activation",lambda:require(not (ROOT/"runtime/prospective_validation/activation_record.json").exists()))
for token in ("requests","urllib","httpx","aiohttp","socket","selenium","yfinance","openai","transformers","torch","tensorflow","sklearn"):case("ZERO",token,lambda token=token:require(token not in CTX["imports"]))
for phrase in ("Stage 6 won","Stage 5D won","improved return","avoided loss","better drawdown","superior hit rate","synthetic P&L","hypothetical quantity"):case("NO_OUTCOME",phrase,lambda phrase=phrase:require(phrase.lower() not in CTX["impl_lower"]))
for i in range(170):case("REPLAY",str(i),lambda:require(build_session(CTX["activation"],EXPECTED_PROTOCOL_HASH,CTX["session1"]["control_database_id"],CTX["run1"],2)==CTX["session1"]))
case("STATUS","ready",lambda:require("READY_FOR_MANUAL_ACTIVATION" in (ROOT/"Stage6_8A_Delivery_Report.md").read_text()));case("STATUS","not active",lambda:require("PROSPECTIVE_RUN_ACTIVE" not in (ROOT/"Stage6_8A_Delivery_Report.md").read_text()));case("STATUS","6.9 deferred",lambda:require("Stage 6.9" in (ROOT/"Stage6_8A_Delivery_Report.md").read_text()))

def make_activation(path):
 value={"schema_version":ACTIVATION_SCHEMA,"activation_id":"","protocol_id":PROTOCOL_ID,"protocol_hash":EXPECTED_PROTOCOL_HASH,"policy_id":POLICY_ID,"policy_hash":EXPECTED_POLICY_HASH,"contract_id":CONTRACT_VERSION,"contract_hash":EXPECTED_CONTRACT_HASH,"stage6_7_closure_baseline":BASELINE,"stage6_8a_activation_head":"f"*40,"branch":BRANCH,"stage5d5_control_tag":CONTROL_TAG,"stage5d5_control_commit":CONTROL_COMMIT,"stage5d_subtree_verification":"PASS","stage6_7b_schema":SHADOW_SCHEMA,"stage6_7b_policy_id":SHADOW_POLICY,"stage6_7b_policy_hash":SHADOW_POLICY_HASH,"stage6_7b_contract_id":SHADOW_CONTRACT,"stage6_7b_contract_hash":SHADOW_CONTRACT_HASH,"stage6_7b_decision_engine_version":SHADOW_ENGINE,"stage6_7b_decision_code_hash":SHADOW_CODE_HASH,"activated_at_utc":"2026-09-30T10:00:00Z","activation_date_ist":"2026-09-30","minimum_completed_control_sessions":20,"performance_based_early_stopping":"PROHIBITED","authority":AUTHORITY,"trading_authority":False,"record_hash":""};value["activation_id"]="S6PROSACT_"+canonical_hash(without(value,"activation_id","record_hash"))[:24];value["record_hash"]=canonical_hash(without(value,"record_hash"));Path(path).write_text(json.dumps(value,sort_keys=True,indent=2)+"\n",encoding="utf-8");return value
def create_control(path):
 c=sqlite3.connect(path);c.executescript("""PRAGMA foreign_keys=ON;CREATE TABLE ledger_meta(singleton INTEGER PRIMARY KEY,schema_version TEXT,database_id TEXT,created_at_utc TEXT);CREATE TABLE stage5d5_meta(singleton INTEGER PRIMARY KEY,schema_version TEXT);CREATE TABLE allocation_runs(allocation_run_id TEXT PRIMARY KEY);CREATE TABLE stage5d5_live_runs(run_id TEXT PRIMARY KEY,market_session_date TEXT UNIQUE,run_started_utc TEXT,run_completed_utc TEXT,data_provider TEXT,market_data_hash TEXT,candidate_input_hash TEXT,candidate_count INTEGER,stage4a3_snapshot_id TEXT,allocation_run_id TEXT,management_session_run_id TEXT,recommendation_count INTEGER,news_status TEXT,canonical_payload_json TEXT,payload_sha256 TEXT);CREATE TABLE recommendations(recommendation_id TEXT PRIMARY KEY,allocation_run_id TEXT,signal_id TEXT,ticker TEXT,signal_date TEXT,decision_date TEXT,portfolio_action_status TEXT,recommended_quantity INTEGER,selected_horizon TEXT,management_policy_id TEXT,entry_low TEXT,entry_high TEXT,stop TEXT,target_1 TEXT,target_2 TEXT,persisted_at_utc TEXT,canonical_payload_json TEXT,payload_sha256 TEXT);CREATE TABLE recommendation_events(event_sequence INTEGER PRIMARY KEY AUTOINCREMENT,event_id TEXT UNIQUE,recommendation_id TEXT,event_type TEXT,effective_date TEXT,recorded_at_utc TEXT,payload_json TEXT,payload_sha256 TEXT,idempotency_key TEXT UNIQUE);""");c.execute("INSERT INTO ledger_meta VALUES(1,'STAGE5D2_SCHEMA_V1','CONTROL_DB','2026-09-30T00:00:00Z')");c.execute("INSERT INTO stage5d5_meta VALUES(1,?)",(CONTROL_SCHEMA,));
 for i,(day,count) in enumerate((("2026-10-01",0),("2026-10-02",2)),1):
  p={"run_id":f"RUN{i}","market_session_date":day,"run_started_utc":day+"T08:00:00Z","run_completed_utc":day+"T09:00:00Z","data_provider":"FIXTURE","market_data_hash":f"MARKET{i}","candidate_input_hash":f"CANDIDATE{i}","candidate_count":count,"stage4a3_snapshot_id":f"S4A3_{i}","allocation_run_id":f"ALLOC{i}","management_session_run_id":f"MGMT{i}","recommendation_count":count,"news_status":"AVAILABLE"};text=cjson(p);c.execute("INSERT INTO allocation_runs VALUES(?)",(p["allocation_run_id"],));c.execute("INSERT INTO stage5d5_live_runs VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",(*[p[k] for k in ("run_id","market_session_date","run_started_utc","run_completed_utc","data_provider","market_data_hash","candidate_input_hash","candidate_count","stage4a3_snapshot_id","allocation_run_id","management_session_run_id","recommendation_count","news_status")],text,payload_sha256(text)))
 for n in (1,2):
  p={"recommendation_id":f"REC{n}","allocation_run_id":"ALLOC2","signal_id":f"SIG{n}","ticker":"AAA.NS","signal_date":"2026-10-01","decision_date":"2026-10-02","portfolio_action_status":"ACTIONABLE_BUY","recommended_quantity":10,"selected_horizon":"SWING","management_policy_id":"POL","entry_low":"100","entry_high":"105","stop":"95","target_1":"115","target_2":"125","thesis_id":"THESIS1"};text=cjson(p);c.execute("INSERT INTO recommendations VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",(*[p[k] for k in ("recommendation_id","allocation_run_id","signal_id","ticker","signal_date","decision_date","portfolio_action_status","recommended_quantity","selected_horizon","management_policy_id","entry_low","entry_high","stop","target_1","target_2")],"2026-10-02T08:10:00Z",text,payload_sha256(text)));e={"recommendation_id":p["recommendation_id"],"event_type":"PENDING_ENTRY","effective_date":"2026-10-02"};et=cjson(e);c.execute("INSERT INTO recommendation_events(event_id,recommendation_id,event_type,effective_date,recorded_at_utc,payload_json,payload_sha256,idempotency_key) VALUES(?,?,?,?,?,?,?,?)",(f"EVT{n}",p["recommendation_id"],"PENDING_ENTRY","2026-10-02","2026-10-02T08:20:00Z",et,payload_sha256(et),f"KEY{n}"))
 c.commit();c.close()
def create_shadow(root,activation_path):
 root.mkdir();path=root/"proposal.sqlite3";c=sqlite3.connect(path);c.executescript("CREATE TABLE morning_revalidation_proposal_store_meta(singleton INTEGER,store_schema TEXT);CREATE TABLE morning_revalidation_proposal_policies(policy_id TEXT,policy_hash TEXT);CREATE TABLE morning_revalidation_proposal_contracts(contract_version TEXT,contract_hash TEXT);CREATE TABLE morning_revalidation_code_manifests(manifest_version TEXT,decision_code_hash TEXT);CREATE TABLE morning_revalidation_proposals(proposal_id TEXT,canonical_json TEXT);");c.execute("INSERT INTO morning_revalidation_proposal_store_meta VALUES(1,'STAGE6_7B_MORNING_REVALIDATION_PROPOSAL_STORE_V1')");c.execute("INSERT INTO morning_revalidation_proposal_policies VALUES(?,?)",(SHADOW_POLICY,SHADOW_POLICY_HASH));c.execute("INSERT INTO morning_revalidation_proposal_contracts VALUES(?,?)",(SHADOW_CONTRACT,SHADOW_CONTRACT_HASH));c.execute("INSERT INTO morning_revalidation_code_manifests VALUES('STAGE6_7B_DECISION_CODE_MANIFEST_V1',?)",(SHADOW_CODE_HASH,));p={"schema_version":SHADOW_SCHEMA,"proposal_id":"PROP1","policy_id":SHADOW_POLICY,"policy_hash":SHADOW_POLICY_HASH,"contract_version":SHADOW_CONTRACT,"contract_hash":SHADOW_CONTRACT_HASH,"decision_engine_version":SHADOW_ENGINE,"decision_code_hash":SHADOW_CODE_HASH,"authority":AUTHORITY,"trading_authority":False,"execution_status":"NOT_AUTHORIZED","stage5d_mutation_status":"PROHIBITED","target_session_date":"2026-10-02","recommendation_id":"REC2","ticker":"AAA.NS","thesis_id":"THESIS1","proposal_decision":"WAIT","proposal_reason_code":"ADVERSE_MATERIAL_CHANGE","proposal_cutoff":"2026-10-02T07:45:00Z","record_hash":""};p["record_hash"]=canonical_hash(without(p,"record_hash"));c.execute("INSERT INTO morning_revalidation_proposals VALUES(?,?)",(p["proposal_id"],canonical_json(p)));c.commit();c.close();create_runtime_origin_marker(root,path,activation_path);return path,p
def setup(temp):
 root=Path(temp.name);adir=root/"activation";absent=root/"absent";old_req,old_now=activation._require_repository,activation._now_utc;activation._require_repository=lambda repo:(verify_configuration(),"f"*40);activation._now_utc=lambda:datetime(2026,9,30,10,0,tzinfo=timezone.utc)
 try:a=activation.activate(root/"fake_repo",adir)["activation"]
 finally:activation._require_repository,activation._now_utc=old_req,old_now
 CTX.update({"activation":a,"activation_dir":adir,"absent_dir":absent,"reactivate":lambda:activation.activate(root/"fake_repo",adir)})
 control_db=root/"control.sqlite3";create_control(control_db);before=file_hash(control_db);control=Stage5DControlReader(control_db);schema_before=list(control.connection.execute("SELECT type,name,sql FROM sqlite_master ORDER BY type,name"));rows_before={t:control.connection.execute(f"SELECT count(*) FROM {t}").fetchone()[0] for t in ("stage5d5_live_runs","recommendations","recommendation_events")};result=control.verify_integrity();CTX.update({"control":control,"control_db":control_db,"control_before":before,"control_result":result["result"],"control_query_only":result["query_only"],"control_schema_before":schema_before,"control_rows_before":rows_before})
 store=ProspectiveValidationStore(root/"prospective.sqlite3",adir/"activation_record.json");CTX["store"]=store
 def out_of_order():
  s=ProspectiveValidationStore(root/"out.sqlite3",adir/"activation_record.json")
  try:return s.enroll_session(control_database=control_db,run_id="RUN2")
  finally:s.close()
 CTX["out_of_order"]=out_of_order;s0=store.enroll_session(control_database=control_db,run_id="RUN1")["session"];s1=store.enroll_session(control_database=control_db,run_id="RUN2")["session"];CTX["session_replay"]=store.enroll_session(control_database=control_db,run_id="RUN2")["status"];run1=control.get_run("RUN2");CTX.update({"session0":s0,"session1":s1,"run1":run1})
 control_case=store.enroll_case(control_database=control_db,session_enrollment_id=s1["enrollment_id"],recommendation_id="REC1")["case"];CTX["case_replay"]=store.enroll_case(control_database=control_db,session_enrollment_id=s1["enrollment_id"],recommendation_id="REC1")["status"]
 shadow_root=root/"shadow_runtime";shadow_db,proposal=create_shadow(shadow_root,adir/"activation_record.json");sr=Stage6ShadowReader(shadow_db,shadow_root,a);CTX["shadow_query_only"]=sr.verify_integrity()["query_only"];sr.close();paired=store.enroll_case(control_database=control_db,session_enrollment_id=s1["enrollment_id"],recommendation_id="REC2",shadow_database=shadow_db,shadow_runtime_root=shadow_root,proposal_id="PROP1");CTX.update({"control_case":control_case,"paired_case":paired["case"],"submission":paired["shadow_submission"],"shadow_db":shadow_db,"proposal":proposal,"rec2":control.get_recommendation("REC2")})
 CTX["control_schema_after"]=list(control.connection.execute("SELECT type,name,sql FROM sqlite_master ORDER BY type,name"));CTX["control_rows_after"]={t:control.connection.execute(f"SELECT count(*) FROM {t}").fetchone()[0] for t in ("stage5d5_live_runs","recommendations","recommendation_events")}
 def restart():
  s=ProspectiveValidationStore(store.database,adir/"activation_record.json")
  try:return s.integrity_check()["result"]
  finally:s.close()
 def tamper(table,stmt):
  path=root/("tamper_"+table+".sqlite3");path.write_bytes(store.connection.serialize());s=ProspectiveValidationStore(path,adir/"activation_record.json")
  try:s.connection.execute(f"DROP TRIGGER protect_{table}_update");s.connection.execute(stmt);s.connection.commit();return s.integrity_check()
  finally:s.close()
 CTX["restart"]=restart;CTX["tamper"]=tamper;CTX["trigger_loss"]=lambda:tamper("prospective_sessions","UPDATE prospective_sessions SET record_hash=record_hash")
 texts=[p.read_text(encoding="utf-8") for p in (ROOT/"stage6_prospective_validation").glob("*.py")];CTX["impl_lower"]="\n".join(texts).lower();CTX["imports"]={((node.module or "").split(".")[0] if isinstance(node,ast.ImportFrom) else node.names[0].name.split(".")[0]) for text in texts for node in ast.walk(ast.parse(text)) if isinstance(node,(ast.Import,ast.ImportFrom))}
def main():
 temp=tempfile.TemporaryDirectory();rows=[];failed=0
 try:
  setup(temp)
  for i,(group,name,fn) in enumerate(CASES,1):
   try:fn();result,detail="PASS",""
   except Exception as exc:result,detail="FAIL",f"{type(exc).__name__}: {exc}";failed+=1
   rows.append({"test_id":i,"test_group":group,"test_name":name,"result":result,"detail":detail})
  OUT.parent.mkdir(parents=True,exist_ok=True)
  with OUT.open("w",newline="",encoding="utf-8") as h:w=csv.DictWriter(h,fieldnames=("test_id","test_group","test_name","result","detail"),lineterminator="\n");w.writeheader();w.writerows(rows)
  print(f"Stage 6.8A: {len(rows)-failed}/{len(rows)} PASS"+(f", {failed} FAIL" if failed else ""));[print((x["test_id"],x["test_group"],x["test_name"],x["detail"])) for x in rows if x["result"]=="FAIL"];return 1 if failed else 0
 finally:
  for key in ("store","control"):
   try:CTX[key].close()
   except Exception:pass
  temp.cleanup()
if __name__=="__main__":raise SystemExit(main())
