from copy import deepcopy
from stage6_ingestion.canonical import canonical_hash,parse_utc,without
from .errors import Stage6AnalogueFeatureError
SCHEMA_VERSION="STAGE6_ANALOGUE_FEATURE_SNAPSHOT_V1";FIELDS=("event_type","severity","materiality","stock_return_state","volume","volatility","technical_structure","sector_behaviour","market_regime","commodity_context","currency_context","rate_context")
SAFETY={"feature_normalization_status":"NOT_APPLIED","feature_weights_status":"NOT_DEFINED","similarity_metric_status":"NOT_EVALUATED","analogue_selection_status":"NOT_EVALUATED","future_outcomes_status":"NOT_ATTACHED","expected_return_status":"NOT_EVALUATED","security_ranking_status":"NOT_EVALUATED","portfolio_influence_status":"NOT_EVALUATED","trading_authority":False}
def _sort(values):return sorted(deepcopy(values),key=lambda x:(x["name"].casefold(),x["unit"],x["observed_at_utc"],x["method"]))
def selection_snapshot(event,payload):
 out={"event_type":event["event_type"],"severity":event["severity"],"materiality":event["materiality"],"stock_return_state":{"returns":deepcopy(payload["stock_returns"]),"gap":deepcopy(payload["gap"])},"volume":deepcopy(payload["volume_anomaly"]),"volatility":deepcopy(payload["volatility"]),"technical_structure":deepcopy(payload["technical_context"]),"sector_behaviour":{"sector_returns":deepcopy(payload["sector_returns"]),"nifty_returns":deepcopy(payload["nifty_returns"]),"relative_strength":deepcopy(payload["relative_strength"])},"market_regime":deepcopy(payload["market_regime"]),"commodity_context":_sort(payload["commodity_context"]),"currency_context":_sort(payload["currency_context"]),"rate_context":_sort(payload["rate_context"])}
 if tuple(out)!=FIELDS:raise Stage6AnalogueFeatureError("ANALOGUE_SELECTION_FIELDS_INVALID")
 return out
def build_feature_snapshot(*,effect,market,event,source_cutoff,policy,policy_hash,feature_contract_hash):
 payload=market["contract_payload"];cutoff=payload["data_cutoff_timestamp"]
 if parse_utc(event["first_known_timestamp"],"first")>parse_utc(event["last_updated_timestamp"],"updated") or parse_utc(event["last_updated_timestamp"],"updated")>parse_utc(cutoff,"cutoff"):raise Stage6AnalogueFeatureError("ANALOGUE_EVENT_CHRONOLOGY_INVALID")
 if parse_utc(source_cutoff,"source_cutoff")>parse_utc(cutoff,"cutoff"):raise Stage6AnalogueFeatureError("ANALOGUE_COMPANY_EFFECT_FROM_FUTURE")
 snapshot=selection_snapshot(event,payload);input_hash=canonical_hash(snapshot)
 identity={"feature_contract_version":"STAGE6_ANALOGUE_FEATURE_CONTRACT_V1","feature_contract_hash":feature_contract_hash,"policy_hash":policy_hash,"processor_version":policy["processor_version"],"company_entity_id":effect["company_entity_id"],"company_effect_record_id":effect["company_effect_record_id"],"company_effect_record_hash":effect["record_hash"],"event_id":event["event_id"],"event_version":event["event_version"],"event_hash":event["record_hash"],"market_context_record_id":market["market_context_record_id"],"market_context_record_hash":market["record_hash"],"as_of_timestamp":payload["as_of_timestamp"],"selection_cutoff":cutoff,"company_effect_source_cutoff":source_cutoff,"selection_input_hash":input_hash,"selection_input_snapshot":snapshot};feature_hash=canonical_hash(identity)
 out={"schema_version":SCHEMA_VERSION,"feature_snapshot_id":"S6ANFEAT_"+feature_hash[:24],"feature_snapshot_hash":feature_hash,"record_hash":"0"*64,"logical_feature_key":"S6ANFEATLOG_"+canonical_hash({"event_id":event["event_id"],"event_version":event["event_version"],"company_entity_id":effect["company_entity_id"],"selection_cutoff":cutoff})[:24],"feature_contract_version":"STAGE6_ANALOGUE_FEATURE_CONTRACT_V1","feature_contract_hash":feature_contract_hash,"policy_id":policy["policy_id"],"policy_hash":policy_hash,"processor_version":policy["processor_version"],"authority":policy["authority"],"company_entity_id":effect["company_entity_id"],"company_effect_record_id":effect["company_effect_record_id"],"company_effect_record_hash":effect["record_hash"],"company_event_effect":effect["company_event_effect"],"exposure_id":effect["exposure_id"],"exposure_version":effect["exposure_version"],"exposure_hash":effect["exposure_hash"],"event_id":event["event_id"],"event_version":event["event_version"],"event_hash":event["record_hash"],"market_context_record_id":market["market_context_record_id"],"market_context_record_hash":market["record_hash"],"as_of_timestamp":payload["as_of_timestamp"],"selection_cutoff":cutoff,"company_effect_source_cutoff":source_cutoff,"selection_input_snapshot":snapshot,"selection_input_hash":input_hash,"pit_verified":True,"leakage_status":"PASS",**SAFETY};out["record_hash"]=canonical_hash(without(out,"record_hash"));return out
