from stage6_ingestion.canonical import canonical_hash,without
SCHEMA_VERSION="STAGE6_EXPOSURE_DIMENSION_QUALIFICATION_V1"
def qualifier_id(transmission,item,policy_hash,processor):return "S6DIMQUAL_"+canonical_hash({"transmission_id":transmission["transmission_id"],"transmission_hash":transmission["record_hash"],"assertion_hash":item["assertion_hash"],"dimension_type":item["dimension_type"],"dimension_entity_id":item["dimension_entity_id"],"evidence_refs":item["evidence_refs"],"policy_hash":policy_hash,"processor_version":processor})[:24]
def qualification_id(transmission,items,policy_hash,processor):return "S6DIM_"+canonical_hash({"schema_version":SCHEMA_VERSION,"transmission_id":transmission["transmission_id"],"transmission_hash":transmission["record_hash"],"qualifiers":items,"policy_id":"S6DIMPOL_STAGE6_3D_V1","policy_hash":policy_hash,"processor_version":processor})[:24]
def build_qualification(*,transmission,binding,exposure,qualifier_items,policy,policy_hash):
 items=sorted(qualifier_items,key=lambda x:(x["assertion_hash"],x["dimension_type"],x["dimension_entity_id"]));items=[{"qualifier_id":qualifier_id(transmission,x,policy_hash,policy["processor_version"]),**x} for x in items]
 rules={r["source_rule_id"]:r for r in policy["rules"]};required=[p for p in transmission["transmission_paths"] if rules[p["rule_id"]]["dimension_mode"]=="EXPLICIT_REQUIRED"];qualified={x["source_path_id"] for x in items};unqualified=sorted(p["path_id"] for p in required if p["path_id"] not in qualified)
 status="NO_COMPATIBLE_PATHS" if not transmission["transmission_paths"] else "ALL_REQUIRED_PATHS_QUALIFIED" if not unqualified else "UNQUALIFIED" if not qualified else "PARTIALLY_QUALIFIED"
 out={"schema_version":SCHEMA_VERSION,"qualification_id":"","record_hash":"0"*64,"transmission_id":transmission["transmission_id"],"transmission_hash":transmission["record_hash"],"binding_id":binding["binding_id"],"binding_hash":binding["record_hash"],"event_id":binding["event_id"],"event_version":binding["event_version"],"event_hash":binding["event_hash"],"exposure_id":exposure["exposure_id"],"exposure_version":exposure["exposure_version"],"exposure_hash":exposure["record_hash"],"company_entity_id":exposure["company_entity_id"],"sector_entity_id":exposure["sector_entity_id"],"subsector_entity_id":exposure["subsector_entity_id"],"entity_registry_snapshot_id":exposure["entity_registry_snapshot_id"],"entity_registry_version":exposure["entity_registry_version"],"entity_registry_hash":exposure["entity_registry_hash"],"qualification_cutoff_timestamp":transmission["evaluation_cutoff_timestamp"],"path_qualification_status":status,"qualifiers":items,"unqualified_path_ids":unqualified,"semantic_compatibility_status":"NOT_EVALUATED","directional_effect_status":"NOT_EVALUATED","magnitude_status":"NOT_EVALUATED","causal_effect_status":"NOT_EVALUATED","policy_id":policy["policy_id"],"policy_hash":policy_hash,"processor_version":policy["processor_version"],"authority":policy["authority"]};out["qualification_id"]=qualification_id(transmission,items,policy_hash,policy["processor_version"]);out["record_hash"]=canonical_hash(without(out,"record_hash"));return out
